# OpenPX SDK sync pipeline
# Usage: just setup && just sync-all

venv := ".venv"

setup:
    python3 -m venv {{venv}}
    {{venv}}/bin/pip install datamodel-code-generator maturin pydantic
    cd sdks/typescript && npm install

sync-all: python node docs
    @echo "All SDKs and docs synced with Rust core"

schema:
    mkdir -p schema
    cargo run -p px-schema > schema/openpx.schema.json

python-models: schema
    {{venv}}/bin/datamodel-codegen \
        --input schema/openpx.schema.json \
        --output sdks/python/python/openpx/_models.py \
        --output-model-type pydantic_v2.BaseModel \
        --target-python-version 3.10 \
        --use-double-quotes

python-build: python-models
    cd sdks/python && PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 ../../{{venv}}/bin/maturin develop --release

python-stubs: python-build
    @echo "Stubs generated by maturin"

python: python-stubs

node-models: schema
    cd sdks/typescript && npx json-schema-to-typescript@15 \
        ../../schema/openpx.schema.json \
        --output types/models.d.ts

node-build: node-models
    cd sdks/typescript && npm run build

node: node-build

docs: schema
    python3 scripts/generate_sdk_docs.py
    @echo "Docs generated in docs/src/content/docs/"

docs-serve: docs
    cd docs && npx astro dev --open

docs-build: docs
    cd docs && npx astro build

docs-install:
    cd docs && npm install

check-sync: schema python-models node-models docs
    git diff --exit-code schema/ sdks/python/python/openpx/_models.py sdks/typescript/types/models.d.ts docs/src/

dashboard:
    cargo run -p px-dashboard

dashboard-release:
    cargo run -p px-dashboard --release
