# OpenPX SDK sync pipeline
# Usage: just setup && just sync-all

venv := ".venv"

setup:
    git config core.hooksPath .githooks
    python3 -m venv {{venv}}
    {{venv}}/bin/pip install datamodel-code-generator maturin pydantic
    cd sdks/typescript && npm install

sync-all: python node docs
    @echo "All SDKs and docs synced with Rust core"

schema:
    mkdir -p schema
    cargo run -p px-schema > schema/openpx.schema.json

python-models: schema
    {{venv}}/bin/datamodel-codegen \
        --input schema/openpx.schema.json \
        --output sdks/python/python/openpx/_models.py \
        --output-model-type pydantic_v2.BaseModel \
        --target-python-version 3.10 \
        --use-double-quotes \
        --disable-timestamp

python-build: python-models
    cd sdks/python && PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 ../../{{venv}}/bin/maturin develop --release

python-stubs: python-build
    @echo "Stubs generated by maturin"

python: python-stubs

node-models: schema
    cd sdks/typescript && npx json-schema-to-typescript@15 \
        ../../schema/openpx.schema.json \
        --output types/models.d.ts

node-build: node-models
    cd sdks/typescript && npm run build

node: node-build

docs: schema
    python3 maintenance/scripts/generate_mintlify_docs.py

docs-serve: docs
    cd docs && mintlify dev

check-sync: schema python-models node-models docs
    git diff --exit-code schema/ sdks/python/python/openpx/_models.py sdks/typescript/types/models.d.ts docs/reference/

drift-check:
    python3 maintenance/scripts/check_docs_drift.py

drift-update:
    python3 maintenance/scripts/check_docs_drift.py --update --full

# Manually trigger the agent-tick workflow (the same workflow the weekly cron runs).
# Use this when an upstream change happens between weekly ticks.
maintain:
    gh workflow run agent-tick.yml --ref main
    @echo "Dispatched agent-tick.yml. Track progress: gh run watch"

# One-time: create the GitHub label taxonomy used by the autonomous-maintenance agents.
labels:
    bash maintenance/scripts/bootstrap-labels.sh

# ---------------------------------------------------------------------------
# Versioning
# ---------------------------------------------------------------------------

# Bump version across all packages: just bump 0.2.0
bump VERSION:
    @echo "Bumping all packages to {{VERSION}}..."
    sed -i'' -e 's/^version = ".*"/version = "{{VERSION}}"/' Cargo.toml
    sed -i'' -e 's/^version = ".*"/version = "{{VERSION}}"/' sdks/python/pyproject.toml
    cd sdks/typescript && npm version "{{VERSION}}" --no-git-tag-version
    sed -i'' -e 's/\(px-core\|px-exchange-kalshi\|px-exchange-polymarket\|px-sports\|px-crypto\|openpx\) = { version = "[^"]*"/\1 = { version = "{{VERSION}}"/' Cargo.toml
    @echo "Done. Verify with: just check-versions"

# Verify all package versions match
check-versions:
    #!/usr/bin/env bash
    RUST=$(grep -m1 '^version' Cargo.toml | sed 's/.*"\(.*\)"/\1/')
    PYTHON=$(grep -m1 '^version' sdks/python/pyproject.toml | sed 's/.*"\(.*\)"/\1/')
    NODE=$(node -p "require('./sdks/typescript/package.json').version")
    echo "Rust:       $RUST"
    echo "Python:     $PYTHON"
    echo "TypeScript: $NODE"
    if [ "$RUST" != "$PYTHON" ] || [ "$RUST" != "$NODE" ]; then
        echo "ERROR: Version mismatch!"
        exit 1
    fi
    echo "All versions in sync."

# ---------------------------------------------------------------------------
# Publishing
# ---------------------------------------------------------------------------

# Publish all Rust crates to crates.io (respects dependency order)
publish-crates:
    cargo publish -p px-core
    sleep 30
    cargo publish -p px-exchange-kalshi
    cargo publish -p px-exchange-polymarket
    cargo publish -p px-crypto
    cargo publish -p px-sports
    sleep 30
    cargo publish -p openpx

# Build and publish Python SDK to PyPI
publish-python: python-build
    cd sdks/python && {{venv}}/bin/maturin publish --skip-existing

# Build and publish Node.js SDK to npm
publish-node: node-build
    cd sdks/typescript && npm publish --access public

# Publish everything
publish-all: publish-crates publish-python publish-node

# Run live integration tests against real exchange APIs
# Usage: just live-test [exchange]
# Examples:
#   just live-test              # all exchanges
#   just live-test kalshi       # single exchange
live-test *FILTER:
    OPENPX_LIVE_TESTS=1 cargo test -p openpx --test live {{FILTER}} -- --nocapture
