/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "LiquidityRole".
 */
export type LiquidityRole = "maker" | "taker";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CryptoPriceSource".
 */
export type CryptoPriceSource = "binance" | "chainlink";
/**
 * Filter for market status in fetch queries.
 *
 * Unlike `MarketStatus` (which represents a market's actual status), this enum includes an `All` variant for fetching markets regardless of status.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketStatusFilter".
 */
export type MarketStatusFilter = "active" | "closed" | "resolved" | "all";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderSide".
 */
export type OrderSide = "buy" | "sell";
/**
 * Why a specific book was invalidated — handed to users so they can decide whether to alert, log, or handle it silently.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "InvalidationReason".
 */
export type InvalidationReason =
  | ("Reconnect" | "Lag" | "ExchangeReset")
  | {
      SequenceGap: {
        expected: number;
        received: number;
        [k: string]: unknown;
      };
    };
/**
 * Market type classification.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketType".
 */
export type MarketType = "binary" | "categorical" | "scalar";
/**
 * Normalized market status across all exchanges.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketStatus".
 */
export type MarketStatus = "active" | "closed" | "resolved";
/**
 * Order time-in-force / execution type.
 *
 * Normalized across all exchanges: - `Gtc` (good-til-cancelled) — rests on the book until filled or cancelled. - `Ioc` (immediate-or-cancel) — fills what it can immediately, cancels the rest. - `Fok` (fill-or-kill) — must fill entirely in one shot or is cancelled.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderType".
 */
export type OrderType = "gtc" | "ioc" | "fok";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = "pending" | "open" | "filled" | "partially_filled" | "cancelled" | "rejected";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "number".
 */
export type Number = number;
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceHistoryInterval".
 */
export type PriceHistoryInterval = "1m" | "1h" | "6h" | "1d" | "1w" | "max";
/**
 * Bid or ask side. Serializes as "bid"/"ask" on the wire.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevelSide".
 */
export type PriceLevelSide = "bid" | "ask";
/**
 * Connection-level events, emitted on a channel separate from `WsUpdate` so a reconnect is observable as a single global signal rather than per-market.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SessionEvent".
 */
export type SessionEvent =
  | {
      kind: "Connected";
      [k: string]: unknown;
    }
  | {
      gap_ms: number;
      kind: "Reconnected";
      [k: string]: unknown;
    }
  | {
      dropped: number;
      first_seq: number;
      kind: "Lagged";
      last_seq: number;
      [k: string]: unknown;
    }
  | {
      kind: "BookInvalidated";
      market_id: string;
      reason: InvalidationReason;
      [k: string]: unknown;
    }
  | {
      kind: "Error";
      message: string;
      [k: string]: unknown;
    };
/**
 * Every per-market event the WebSocket surface emits. Closed tagged union; no untyped escape hatch in the stable enum. If an exchange grows a payload we want to surface in raw form, add a separate `raw_events()` stream rather than another `WsUpdate` variant — keeps consumer `match` exhaustiveness honest.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "WsUpdate".
 */
export type WsUpdate =
  | {
      asset_id: string;
      book: Orderbook;
      exchange_ts?: number | null;
      kind: "Snapshot";
      local_ts_ms: number;
      market_id: string;
      seq: number;
      [k: string]: unknown;
    }
  | {
      asset_id: string;
      changes: PriceLevelChange[];
      exchange_ts?: number | null;
      kind: "Delta";
      local_ts_ms: number;
      market_id: string;
      seq: number;
      [k: string]: unknown;
    }
  | {
      asset_id: string;
      kind: "Clear";
      local_ts_ms: number;
      market_id: string;
      reason: InvalidationReason;
      seq: number;
      [k: string]: unknown;
    }
  | {
      kind: "Trade";
      local_ts_ms: number;
      trade: ActivityTrade;
      [k: string]: unknown;
    }
  | {
      fill: ActivityFill;
      kind: "Fill";
      local_ts_ms: number;
      [k: string]: unknown;
    };

/**
 * Auto-generated JSON Schema for OpenPX core types
 */
export interface OpenPX {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ActivityFill".
 */
export interface ActivityFill {
  asset_id: string;
  /**
   * Exchange-authoritative timestamp (millis since epoch).
   */
  exchange_ts_ms?: number | null;
  /**
   * Fee charged for this fill, when the exchange publishes one.
   */
  fee?: number | null;
  fill_id?: string | null;
  liquidity_role?: LiquidityRole | null;
  market_id: string;
  order_id?: string | null;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  /**
   * On-chain transaction hash, when the exchange publishes one.
   */
  tx_hash?: string | null;
  [k: string]: unknown;
}
/**
 * Activity events still carried inside `WsUpdate::Trade` / `WsUpdate::Fill`. Retained as a typed payload alongside the stream rather than as a separate per-token surface.
 *
 * `exchange_ts_ms` is exchange-authoritative millis since epoch — uniform with `WsUpdate::{Snapshot, Delta}::exchange_ts`, so every timestamp on the WS surface is the same type (`u64` millis). `chrono::DateTime` was more expressive but cost a representation mismatch at every FFI boundary.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ActivityTrade".
 */
export interface ActivityTrade {
  aggressor_side?: string | null;
  asset_id: string;
  /**
   * Exchange-authoritative timestamp (millis since epoch).
   */
  exchange_ts_ms?: number | null;
  /**
   * Fee rate in basis points (e.g. 0 = no fee, 200 = 2%). Polymarket `last_trade_price` events populate this.
   */
  fee_rate_bps?: number | null;
  market_id: string;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  trade_id?: string | null;
  [k: string]: unknown;
}
/**
 * OHLCV candlestick, normalized across all exchanges. Prices are decimals (0.0 to 1.0). Timestamp is the period START (not end). Serialized over the wire as RFC3339 (DateTime<Utc>) for API consistency.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Candlestick".
 */
export interface Candlestick {
  close: number;
  high: number;
  low: number;
  open: number;
  /**
   * Open interest at this candle's close. Only available from exchanges that report it (e.g., Kalshi).
   */
  open_interest?: number | null;
  /**
   * Period start timestamp (UTC). lightweight-charts expects start-of-period.
   */
  timestamp: string;
  /**
   * Trade volume in contracts. 0.0 if exchange doesn't provide volume.
   */
  volume: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CryptoPrice".
 */
export interface CryptoPrice {
  source: CryptoPriceSource;
  symbol: string;
  timestamp: number;
  value: number;
  [k: string]: unknown;
}
/**
 * A grouping of related markets. On Kalshi, an Event is a single resolution (e.g. "Will Candidate X win State Y?") with one or more contracts. On Polymarket, an Event is the parent of one or more Markets sharing a common theme (e.g. "2028 US Presidential Election" with markets per candidate).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  category?: string | null;
  description?: string | null;
  end_ts?: string | null;
  last_updated_ts?: string | null;
  /**
   * Sibling market market_tickers under this event — unified `Market.ticker` values (Kalshi market market_tickers; Polymarket slugs).
   */
  market_tickers?: string[];
  mutually_exclusive?: boolean | null;
  /**
   * Polymarket's numeric REST id for the event (e.g. `"12585"`). None on Kalshi (no separate numeric event surface).
   */
  numeric_id?: string | null;
  open_interest?: number | null;
  /**
   * Parent series ticker. Kalshi: upstream `series_ticker`. Polymarket: the embedded series's `ticker` (or `slug` if `ticker` is null).
   */
  series_ticker?: string | null;
  start_ts?: string | null;
  status?: string | null;
  /**
   * Native event identifier. Kalshi: `event_ticker` (e.g. `"KXPRES-2028"`). Polymarket: the event slug (e.g. `"presidential-election-winner-2024"`).
   */
  ticker: string;
  title: string;
  volume?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ExchangeInfo".
 */
export interface ExchangeInfo {
  has_approvals: boolean;
  has_cancel_all_orders: boolean;
  has_cancel_order: boolean;
  has_create_order: boolean;
  has_create_orders_batch: boolean;
  has_fetch_balance: boolean;
  has_fetch_fills: boolean;
  has_fetch_last_trade_price: boolean;
  has_fetch_market_lineage: boolean;
  has_fetch_market_tags: boolean;
  has_fetch_markets: boolean;
  has_fetch_midpoint: boolean;
  has_fetch_midpoints_batch: boolean;
  has_fetch_open_interest: boolean;
  has_fetch_orderbook: boolean;
  has_fetch_orderbook_history: boolean;
  has_fetch_orderbooks_batch: boolean;
  has_fetch_positions: boolean;
  has_fetch_price_history: boolean;
  has_fetch_server_time: boolean;
  has_fetch_spread: boolean;
  has_fetch_trades: boolean;
  has_fetch_user_activity: boolean;
  has_fetch_user_trades: boolean;
  has_refresh_balance: boolean;
  has_websocket: boolean;
  id: string;
  name: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "FetchMarketsParams".
 */
export interface FetchMarketsParams {
  /**
   * Exchange-specific cursor (offset, page number, or cursor string)
   */
  cursor?: string | null;
  /**
   * Fetch all markets within a specific event. Pass a Kalshi event ticker (e.g., `"KXBTC-25MAR14"`) or a Polymarket event slug (e.g., `"will-trump-win-2024"`). Polymarket numeric event IDs are not accepted — they will be supported via a future `event_numeric_id` field. When set, `cursor` and `limit` are ignored (not paginated). `status` filtering is still applied client-side.
   */
  event_ticker?: string | null;
  /**
   * Per-page limit. Each exchange applies its own server-side cap: Kalshi tops out at 1000, Polymarket at ~500. Values above the cap are silently clamped to the cap.
   */
  limit?: number | null;
  /**
   * Fetch a specific set of markets by their unified ticker. Each entry is a Kalshi market ticker (e.g., `"KXBTCD-25APR1517"`) or a Polymarket market slug (e.g., `"will-trump-win-2024"`). When non-empty, `cursor`, `event_ticker`, and `series_ticker` are ignored.
   */
  market_tickers?: string[];
  /**
   * Filter by series ticker. Pass a Kalshi series ticker (e.g., `"KXBTC"`) to fetch only markets in that series. Polymarket support arrives once `series_numeric_id` is added to this struct — until then, this field is ignored on Polymarket.
   */
  series_ticker?: string | null;
  /**
   * Filter by market status. Defaults to Active at the exchange level when None. Use `MarketStatusFilter::All` to fetch markets of any status.
   */
  status?: MarketStatusFilter | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "FetchOrdersParams".
 */
export interface FetchOrdersParams {
  market_ticker?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "FetchUserActivityParams".
 */
export interface FetchUserActivityParams {
  address: string;
  limit?: number | null;
  [k: string]: unknown;
}
/**
 * A single fill (trade execution) from a user's order.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Fill".
 */
export interface Fill {
  created_at: string;
  fee: number;
  fill_id: string;
  is_taker: boolean;
  market_ticker: string;
  order_id: string;
  outcome: string;
  price: number;
  side: OrderSide;
  size: number;
  [k: string]: unknown;
}
/**
 * Last public trade price + side + size for a market outcome. Distinct from the full `MarketTrade` tape: this is just "what just printed?" — common UI need that doesn't require the full trade history.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "LastTrade".
 */
export interface LastTrade {
  price: number;
  side: OrderSide;
  size: number;
  ts_ms: number;
  [k: string]: unknown;
}
/**
 * Unified prediction market model.
 *
 * All exchanges produce this single type directly — no intermediate conversion.
 *
 * # Price Format
 *
 * All prices are normalized to decimal format (0.0 to 1.0). Exchange-specific conversions are handled during parsing:
 *
 * - **Kalshi**: Fixed-point dollar strings parsed directly (post March 2026 migration). - **Polymarket**: Native prices already in decimal (0.0-1.0).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Market".
 */
export interface Market {
  /**
   * Best ask price (normalized 0-1)
   */
  best_ask?: number | null;
  /**
   * Best bid price (normalized 0-1)
   */
  best_bid?: number | null;
  /**
   * Market close time
   */
  close_time?: string | null;
  /**
   * Polymarket CTF condition id
   */
  condition_id?: string | null;
  /**
   * Market creation time
   */
  created_at?: string | null;
  /**
   * Native event identifier this market belongs to. Kalshi: upstream `event_ticker`. Polymarket: the parent event's `slug`.
   */
  event_ticker?: string | null;
  /**
   * Exchange identifier (kalshi, polymarket)
   */
  exchange: string;
  /**
   * Last trade price (normalized 0-1)
   */
  last_trade_price?: number | null;
  /**
   * Market type classification
   */
  market_type: MarketType;
  /**
   * Minimum order size (contracts). Kalshi: synthesized — 1.0, or 0.01 when fractional_trading_enabled. Polymarket: read directly from `orderMinSize`.
   */
  min_order_size?: number | null;
  /**
   * Polymarket: neg-risk flag
   */
  neg_risk?: boolean | null;
  /**
   * Polymarket: neg-risk market ID
   */
  neg_risk_market_id?: string | null;
  /**
   * Polymarket's numeric DB id (e.g. "1031769"). Exposed for callers that need to build UI deep-links or cross-reference Polymarket's REST-only numeric surface. Not used for trading or subscription.
   */
  numeric_id?: string | null;
  /**
   * Market open time
   */
  open_time?: string | null;
  /**
   * Primary key: {exchange}:{ticker}
   */
  openpx_id: string;
  /**
   * Ordered list of outcomes. Each entry carries label, price, and (if exposed) token id. Polymarket categorical markets have N entries; Kalshi binary markets always have 2 ("Yes" / "No").
   */
  outcomes?: Outcome[];
  /**
   * Resolution result. Kalshi: enum string from upstream. Polymarket: derived winning-outcome label (the `outcomes[i]` whose `outcomePrices[i]` is 1.0 after settlement). None for unresolved markets.
   */
  result?: string | null;
  /**
   * Resolution rules. Kalshi: `{rules_primary} | {rules_secondary}`. Polymarket: `description`.
   */
  rules?: string | null;
  /**
   * Settlement / resolution time. Kalshi: `settlement_ts`. Polymarket: `closedTime` (populated only after on-chain settlement).
   */
  settlement_time?: string | null;
  /**
   * Normalized status: Active, Closed, Resolved
   */
  status: MarketStatus;
  /**
   * Minimum price increment in dollars. Polymarket: `orderPriceMinTickSize` directly. Kalshi: the smallest `step` across the tiered `price_ranges` array (the finest precision the market accepts anywhere on its price curve — orders in coarser tiers must still round to that tier's step).
   */
  tick_size?: number | null;
  /**
   * Native exchange ticker. Kalshi: `ticker`. Polymarket: `slug`.
   */
  ticker: string;
  /**
   * Market title
   */
  title: string;
  /**
   * Total volume (USD)
   */
  volume: number;
  /**
   * 24-hour trading volume (USD)
   */
  volume_24h?: number | null;
  [k: string]: unknown;
}
/**
 * One outcome of a prediction market — label, current price, and (where the exchange exposes one) the on-chain token id needed to subscribe to its orderbook stream. Replaces the previous trio of `outcome_prices` map + `outcome_tokens` vec + binary-only `token_id_yes`/`token_id_no` with a single ordered list keyed by index.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Outcome".
 */
export interface Outcome {
  /**
   * Outcome label (e.g. "Yes", "No", or a categorical option name).
   */
  label: string;
  /**
   * Current outcome price in [0.0, 1.0]. None when not exposed (e.g. Kalshi markets pre-fill, or Polymarket categorical markets without a price).
   */
  price?: number | null;
  /**
   * CTF token id (Polymarket only). Used to subscribe to per-outcome orderbook streams. None on Kalshi.
   */
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * A market plus the parent event and series that contextualize it.
 *
 * `event` and `series` are `Option` because: - some markets have no parent event surface (Kalshi standalone markets); - the upstream lookup for the parent may legitimately 404 on a dangling reference. A dangling parent should not fail the whole call — the caller still gets the `Market`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketLineage".
 */
export interface MarketLineage {
  event?: Event | null;
  market: Market;
  series?: Series | null;
  [k: string]: unknown;
}
/**
 * A recurring family of events. Examples: a weekly inflation reading, a monthly nonfarm payrolls release, a regular sports season. On Kalshi, a Series is identified by `series_ticker` (e.g. `KXPRES`). On Polymarket, a Series wraps multiple Events with shared metadata.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Series".
 */
export interface Series {
  category?: string | null;
  fee_type?: string | null;
  frequency?: string | null;
  last_updated_ts?: string | null;
  /**
   * Polymarket's numeric REST id for the series (e.g. `"10345"`). None on Kalshi (no separate numeric series surface).
   */
  numeric_id?: string | null;
  settlement_sources?: SettlementSource[];
  tags?: string[];
  /**
   * Native series identifier. Kalshi: `ticker` (e.g. `"KXPRES"`). Polymarket: the series's `ticker` field, falling back to `slug` when `ticker` is null upstream.
   */
  ticker: string;
  title: string;
  volume?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SettlementSource".
 */
export interface SettlementSource {
  name?: string | null;
  url?: string | null;
  [k: string]: unknown;
}
/**
 * Normalized public market trade, suitable for "tape" UIs.
 *
 * - `price` is normalized to [0.0, 1.0] across all exchanges. - `timestamp` is the exchange-provided trade timestamp (UTC).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketTrade".
 */
export interface MarketTrade {
  aggressor_side?: string | null;
  id?: string | null;
  no_price?: number | null;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  taker_address?: string | null;
  timestamp: string;
  tx_hash?: string | null;
  yes_price?: number | null;
  [k: string]: unknown;
}
/**
 * Request for midpoint / spread / last-trade-price methods. The same shape is reused for all three since they target the same outcome and accept the same identifier inputs.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MidpointRequest".
 */
export interface MidpointRequest {
  market_ticker: string;
  outcome?: string | null;
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * One order in a `create_orders_batch` call. Each venue caps the batch size (Polymarket: 15; Kalshi: token-budget-dependent).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "NewOrder".
 */
export interface NewOrder {
  /**
   * Kalshi-specific idempotency key.
   */
  client_order_id?: string | null;
  /**
   * Unix seconds. Required for `OrderType::Gtc` orders that should expire.
   */
  expiration_ts?: number | null;
  market_ticker: string;
  order_type: OrderType;
  outcome: string;
  /**
   * Polymarket: pin maker-only. Ignored on Kalshi.
   */
  post_only?: boolean | null;
  price: number;
  /**
   * Kalshi: only allow size reductions. Maps to `reduce_only=true`.
   */
  reduce_only?: boolean | null;
  side: OrderSide;
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Order".
 */
export interface Order {
  created_at: string;
  filled: number;
  id: string;
  market_ticker: string;
  outcome: string;
  price: number;
  side: OrderSide;
  size: number;
  status: OrderStatus;
  updated_at?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Orderbook".
 */
export interface Orderbook {
  asks: PriceLevel[];
  asset_id: string;
  bids: PriceLevel[];
  /**
   * Exchange-provided hash for verifying book state integrity during replay. Polymarket: present on `book` snapshot events.
   */
  hash?: string | null;
  last_update_id?: number | null;
  market_ticker: string;
  timestamp?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevel".
 */
export interface PriceLevel {
  price: Number;
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookHistoryRequest".
 */
export interface OrderbookHistoryRequest {
  cursor?: string | null;
  end_ts?: number | null;
  limit?: number | null;
  market_ticker: string;
  start_ts?: number | null;
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * Request for fetching an L2 orderbook.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookRequest".
 */
export interface OrderbookRequest {
  market_ticker: string;
  outcome?: string | null;
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * A point-in-time L2 orderbook snapshot, used for historical orderbook data.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookSnapshot".
 */
export interface OrderbookSnapshot {
  asks: PriceLevel[];
  bids: PriceLevel[];
  hash?: string | null;
  recorded_at?: string | null;
  timestamp: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Position".
 */
export interface Position {
  average_price: number;
  current_price: number;
  market_ticker: string;
  outcome: string;
  size: number;
  [k: string]: unknown;
}
/**
 * Request for fetching price history / candlestick data.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceHistoryRequest".
 */
export interface PriceHistoryRequest {
  /**
   * Condition ID for OI enrichment (Polymarket).
   */
  condition_id?: string | null;
  /**
   * Unix seconds
   */
  end_ts?: number | null;
  interval: PriceHistoryInterval;
  market_ticker: string;
  outcome?: string | null;
  /**
   * Unix seconds
   */
  start_ts?: number | null;
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * A single price level change. Absolute replacement semantics: size > 0 = set level to this size, size == 0 = remove level.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevelChange".
 */
export interface PriceLevelChange {
  price: Number;
  side: PriceLevelSide;
  size: number;
  [k: string]: unknown;
}
/**
 * Real-time sports score/state from the Polymarket Sports WebSocket. Serializes as snake_case for end-users; aliases accept the upstream camelCase.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SportResult".
 */
export interface SportResult {
  away_team: string;
  elapsed?: string | null;
  ended: boolean;
  finished_timestamp?: string | null;
  game_id: number;
  home_team: string;
  league_abbreviation: string;
  live: boolean;
  period?: string | null;
  score?: string | null;
  slug: string;
  status: string;
  turn?: string | null;
  [k: string]: unknown;
}
/**
 * Top-of-book bid/ask + spread for a market outcome. Lighter than a full `Orderbook` — useful for liquidity scoring and PnL marks where only the best levels are needed.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Spread".
 */
export interface Spread {
  ask: number;
  bid: number;
  spread: number;
  ts_ms?: number | null;
  [k: string]: unknown;
}
/**
 * A category or tag attached to a market or event. Used for filtering and search. Kalshi exposes tags via category-keyed lookups; Polymarket exposes per-market and per-event tag arrays.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Tag".
 */
export interface Tag {
  id: string;
  name: string;
  slug?: string | null;
  [k: string]: unknown;
}
/**
 * Request for fetching recent public trades ("tape") for a market outcome.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "TradesRequest".
 */
export interface TradesRequest {
  /**
   * Opaque pagination cursor from a previous response.
   */
  cursor?: string | null;
  /**
   * Unix seconds (inclusive)
   */
  end_ts?: number | null;
  /**
   * Max number of trades to return (exchange-specific caps may apply).
   */
  limit?: number | null;
  /**
   * Optional alternate market identifier for trade endpoints (e.g., Polymarket conditionId). When provided, exchanges should prefer this over `market_ticker`.
   */
  market_ref?: string | null;
  /**
   * Exchange-native market identifier.
   */
  market_ticker: string;
  outcome?: string | null;
  /**
   * Unix seconds (inclusive)
   */
  start_ts?: number | null;
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * A user-facing trade row: distinct from `Fill` because it carries auxiliary fields some venues expose (realized PnL, on-chain tx hash, owner wallet) but others do not. Polymarket Data `/trades` returns these natively; Kalshi `/portfolio/fills` returns a subset, with `realized_pnl` and `tx_hash` left as `None`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "UserTrade".
 */
export interface UserTrade {
  asset_id?: string | null;
  condition_id?: string | null;
  fee?: number | null;
  id: string;
  market_ticker: string;
  owner?: string | null;
  price: number;
  realized_pnl?: number | null;
  role?: LiquidityRole | null;
  side: OrderSide;
  size: number;
  ts_ms: number;
  tx_hash?: string | null;
  [k: string]: unknown;
}
/**
 * Request for `fetch_user_trades`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "UserTradesRequest".
 */
export interface UserTradesRequest {
  cursor?: string | null;
  /**
   * Unix seconds (inclusive)
   */
  end_ts?: number | null;
  limit?: number | null;
  market_ticker?: string | null;
  side?: OrderSide | null;
  /**
   * Unix seconds (inclusive)
   */
  start_ts?: number | null;
  /**
   * `None` = caller's own trades (auth required on both venues). `Some(addr)` = public lookup for `addr` (Polymarket only; Kalshi returns `NotSupported`).
   */
  user_address?: string | null;
  [k: string]: unknown;
}
