/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether a fill provided liquidity (`maker`) or took it (`taker`).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "LiquidityRole".
 */
export type LiquidityRole = "maker" | "taker";
/**
 * Time-in-force. Options: `gtc` (rests on book), `ioc` (fill-now-or-cancel-rest), `fok` (all-or-nothing).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderType".
 */
export type OrderType = "gtc" | "ioc" | "fok";
/**
 * Outcome targeted by an order. Options: `yes`, `no`, or `label: "<name>"` for categorical Polymarket markets.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderOutcome".
 */
export type OrderOutcome =
  | ("yes" | "no")
  | {
      label: string;
    };
/**
 * Order direction. Options: `buy`, `sell`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderSide".
 */
export type OrderSide = "buy" | "sell";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CryptoPriceSource".
 */
export type CryptoPriceSource = "binance" | "chainlink";
/**
 * Market status filter for `fetch_markets`. Options: `active`, `closed`, `resolved`, `all`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketStatusFilter".
 */
export type MarketStatusFilter = "active" | "closed" | "resolved" | "all";
/**
 * Why a specific book was invalidated — handed to users so they can decide whether to alert, log, or handle it silently.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "InvalidationReason".
 */
export type InvalidationReason =
  | ("Reconnect" | "Lag" | "ExchangeReset")
  | {
      SequenceGap: {
        expected: number;
        received: number;
        [k: string]: unknown;
      };
    };
/**
 * Shape of a market's outcomes. Options: `binary`, `categorical`, `scalar`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketType".
 */
export type MarketType = "binary" | "categorical" | "scalar";
/**
 * Market lifecycle state. Options: `active`, `closed`, `resolved`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketStatus".
 */
export type MarketStatus = "active" | "closed" | "resolved";
/**
 * Order lifecycle state. Options: `pending`, `open`, `filled`, `partially_filled`, `cancelled`, `rejected`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = "pending" | "open" | "filled" | "partially_filled" | "cancelled" | "rejected";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "number".
 */
export type Number = number;
/**
 * Side of an orderbook level. Options: `bid`, `ask`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevelSide".
 */
export type PriceLevelSide = "bid" | "ask";
/**
 * Connection-level events, emitted on a channel separate from `WsUpdate` so a reconnect is observable as a single global signal rather than per-market.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SessionEvent".
 */
export type SessionEvent =
  | {
      kind: "Connected";
      [k: string]: unknown;
    }
  | {
      gap_ms: number;
      kind: "Reconnected";
      [k: string]: unknown;
    }
  | {
      dropped: number;
      first_seq: number;
      kind: "Lagged";
      last_seq: number;
      [k: string]: unknown;
    }
  | {
      kind: "BookInvalidated";
      market_id: string;
      reason: InvalidationReason;
      [k: string]: unknown;
    }
  | {
      kind: "Error";
      message: string;
      [k: string]: unknown;
    };
/**
 * Every per-market event the WebSocket surface emits. Closed tagged union; no untyped escape hatch in the stable enum. If an exchange grows a payload we want to surface in raw form, add a separate `raw_events()` stream rather than another `WsUpdate` variant — keeps consumer `match` exhaustiveness honest.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "WsUpdate".
 */
export type WsUpdate =
  | {
      asset_id: string;
      book: Orderbook;
      exchange_ts?: number | null;
      kind: "Snapshot";
      local_ts_ms: number;
      market_id: string;
      seq: number;
      [k: string]: unknown;
    }
  | {
      asset_id: string;
      changes: PriceLevelChange[];
      exchange_ts?: number | null;
      kind: "Delta";
      local_ts_ms: number;
      market_id: string;
      seq: number;
      [k: string]: unknown;
    }
  | {
      asset_id: string;
      kind: "Clear";
      local_ts_ms: number;
      market_id: string;
      reason: InvalidationReason;
      seq: number;
      [k: string]: unknown;
    }
  | {
      kind: "Trade";
      local_ts_ms: number;
      trade: ActivityTrade;
      [k: string]: unknown;
    }
  | {
      fill: ActivityFill;
      kind: "Fill";
      local_ts_ms: number;
      [k: string]: unknown;
    };

/**
 * Auto-generated JSON Schema for OpenPX core types
 */
export interface OpenPX {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ActivityFill".
 */
export interface ActivityFill {
  asset_id: string;
  /**
   * Exchange-authoritative timestamp (millis since epoch).
   */
  exchange_ts_ms?: number | null;
  /**
   * Fee charged for this fill, when the exchange publishes one.
   */
  fee?: number | null;
  fill_id?: string | null;
  liquidity_role?: LiquidityRole | null;
  market_id: string;
  order_id?: string | null;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  /**
   * On-chain transaction hash, when the exchange publishes one.
   */
  tx_hash?: string | null;
  [k: string]: unknown;
}
/**
 * Activity events still carried inside `WsUpdate::Trade` / `WsUpdate::Fill`. Retained as a typed payload alongside the stream rather than as a separate per-token surface.
 *
 * `exchange_ts_ms` is exchange-authoritative millis since epoch — uniform with `WsUpdate::{Snapshot, Delta}::exchange_ts`, so every timestamp on the WS surface is the same type (`u64` millis). `chrono::DateTime` was more expressive but cost a representation mismatch at every FFI boundary.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ActivityTrade".
 */
export interface ActivityTrade {
  aggressor_side?: string | null;
  asset_id: string;
  /**
   * Exchange-authoritative timestamp (millis since epoch).
   */
  exchange_ts_ms?: number | null;
  /**
   * Fee rate in basis points (e.g. 0 = no fee, 200 = 2%). Polymarket `last_trade_price` events populate this.
   */
  fee_rate_bps?: number | null;
  market_id: string;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  trade_id?: string | null;
  [k: string]: unknown;
}
/**
 * Input for `create_order`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CreateOrderRequest".
 */
export interface CreateOrderRequest {
  /**
   * The orderable asset — Kalshi market ticker or Polymarket CTF token id (e.g. `"KXBTCD-25APR1517"`).
   */
  asset_id: string;
  /**
   * Time-in-force; defaults to `gtc` (options: `gtc`, `ioc`, `fok`).
   */
  order_type?: OrderType & string;
  /**
   * Outcome to trade. Options: `yes`, `no`, or `label: "<name>"` (Polymarket categorical markets only).
   */
  outcome: OrderOutcome;
  /**
   * Limit price as YES probability in `(0, 1)` (e.g. `0.62`).
   */
  price: number;
  /**
   * Order direction. Options: `buy`, `sell`.
   */
  side: OrderSide;
  /**
   * Order size in contracts (e.g. `100.0`).
   */
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CryptoPrice".
 */
export interface CryptoPrice {
  source: CryptoPriceSource;
  symbol: string;
  timestamp: number;
  value: number;
  [k: string]: unknown;
}
/**
 * Cumulative depth at 10/50/100 bps tiers from mid.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "DepthBuckets".
 */
export interface DepthBuckets {
  /**
   * Cumulative ask size within 100 bps of mid (contracts).
   */
  ask_within_100bps: number;
  /**
   * Cumulative ask size within 10 bps of mid (contracts).
   */
  ask_within_10bps: number;
  /**
   * Cumulative ask size within 50 bps of mid (contracts).
   */
  ask_within_50bps: number;
  /**
   * Cumulative bid size within 100 bps of mid (contracts).
   */
  bid_within_100bps: number;
  /**
   * Cumulative bid size within 10 bps of mid (contracts).
   */
  bid_within_10bps: number;
  /**
   * Cumulative bid size within 50 bps of mid (contracts).
   */
  bid_within_50bps: number;
  [k: string]: unknown;
}
/**
 * A grouping of related markets — one Kalshi event_ticker or one Polymarket event slug.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  /**
   * Topical category (e.g. `"Politics"`); `null` when upstream omits it.
   */
  category?: string | null;
  /**
   * Long-form event description; `null` when upstream omits it.
   */
  description?: string | null;
  /**
   * Event end time in UTC.
   */
  end_ts?: string | null;
  /**
   * Last upstream update time in UTC.
   */
  last_updated_ts?: string | null;
  /**
   * Tickers of markets under this event (e.g. `["KXBTCD-25APR1517"]`).
   */
  market_tickers?: string[];
  /**
   * `true` if exactly one child market resolves YES.
   */
  mutually_exclusive?: boolean | null;
  /**
   * Polymarket numeric event id (e.g. `"12585"`); `null` on Kalshi.
   */
  numeric_id?: string | null;
  /**
   * Open interest in USD (e.g. `5000.0`).
   */
  open_interest?: number | null;
  /**
   * Parent series ticker (e.g. `"KXPRES"`); `null` when the event has no parent series.
   */
  series_ticker?: string | null;
  /**
   * Event start time in UTC.
   */
  start_ts?: string | null;
  /**
   * Upstream lifecycle string (e.g. `"open"`); `null` when upstream omits it.
   */
  status?: string | null;
  /**
   * Native event identifier — Kalshi event ticker or Polymarket event slug (e.g. `"KXPRES-2028"`).
   */
  ticker: string;
  /**
   * Human-readable event title (e.g. `"2028 US Presidential Election"`).
   */
  title: string;
  /**
   * Lifetime trading volume in USD (e.g. `12345.67`).
   */
  volume?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ExchangeInfo".
 */
export interface ExchangeInfo {
  has_approvals: boolean;
  has_cancel_all_orders: boolean;
  has_cancel_order: boolean;
  has_create_order: boolean;
  has_create_orders_batch: boolean;
  has_fetch_balance: boolean;
  has_fetch_fills: boolean;
  has_fetch_market_lineage: boolean;
  has_fetch_markets: boolean;
  has_fetch_orderbook: boolean;
  has_fetch_orderbooks_batch: boolean;
  has_fetch_positions: boolean;
  has_fetch_server_time: boolean;
  has_fetch_trades: boolean;
  has_refresh_balance: boolean;
  has_websocket: boolean;
  id: string;
  name: string;
  [k: string]: unknown;
}
/**
 * Filters for `fetch_markets`. All fields are optional.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "FetchMarketsParams".
 */
export interface FetchMarketsParams {
  /**
   * Opaque cursor returned by a prior page (e.g. `"eyJvIjoxMDB9"`).
   */
  cursor?: string | null;
  /**
   * Fetch all markets in this event — Kalshi event ticker or Polymarket event slug (e.g. `"KXBTC-25MAR14"`).
   */
  event_ticker?: string | null;
  /**
   * Page size; clamped to per-exchange caps (Kalshi 1000, Polymarket 500) (e.g. `100`).
   */
  limit?: number | null;
  /**
   * Fetch only these market tickers — Kalshi tickers or Polymarket slugs (e.g. `["KXBTCD-25APR1517"]`).
   */
  market_tickers?: string[];
  /**
   * Fetch only markets in this Kalshi series ticker (e.g. `"KXBTC"`); ignored on Polymarket today.
   */
  series_ticker?: string | null;
  /**
   * Status filter; defaults to `active` (options: `active`, `closed`, `resolved`, `all`).
   */
  status?: MarketStatusFilter | null;
  [k: string]: unknown;
}
/**
 * A single fill (trade execution) from one of the caller's orders.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Fill".
 */
export interface Fill {
  /**
   * Fill execution time (UTC) (e.g. `"2026-04-25T12:00:00Z"`).
   */
  created_at: string;
  /**
   * Fee paid in quote dollars (e.g. `0.07`).
   */
  fee: number;
  /**
   * Globally-unique fill id (e.g. `"f-9c2..."`).
   */
  fill_id: string;
  /**
   * `true` if the caller took liquidity, `false` if they made it.
   */
  is_taker: boolean;
  /**
   * Unified market ticker the fill belongs to (e.g. `"KXBTCD-25APR1517"`).
   */
  market_ticker: string;
  /**
   * Parent order id (e.g. `"a1b2c3d4-..."`).
   */
  order_id: string;
  /**
   * Outcome label as published by the exchange (e.g. `"Yes"`, `"No"`).
   */
  outcome: string;
  /**
   * Fill price as YES probability in `(0, 1)` (e.g. `0.62`).
   */
  price: number;
  /**
   * Order direction. Options: `buy`, `sell`.
   */
  side: OrderSide;
  /**
   * Filled size in contracts (e.g. `25.0`).
   */
  size: number;
  [k: string]: unknown;
}
/**
 * Per-side resting-level counts.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "LevelCount".
 */
export interface LevelCount {
  /**
   * Number of ask levels (e.g. `12`).
   */
  asks: number;
  /**
   * Number of bid levels (e.g. `12`).
   */
  bids: number;
  [k: string]: unknown;
}
/**
 * A prediction market on the unified surface. Prices are YES probabilities in `[0, 1]`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Market".
 */
export interface Market {
  /**
   * Best ask as YES probability in `[0, 1]` (e.g. `0.63`).
   */
  best_ask?: number | null;
  /**
   * Best bid as YES probability in `[0, 1]` (e.g. `0.61`).
   */
  best_bid?: number | null;
  /**
   * Market close time in UTC (e.g. `"2026-04-25T20:00:00Z"`).
   */
  close_time?: string | null;
  /**
   * Polymarket CTF condition id (e.g. `"0xabc..."`); `null` on Kalshi.
   */
  condition_id?: string | null;
  /**
   * Market creation time in UTC.
   */
  created_at?: string | null;
  /**
   * Parent event ticker — Kalshi event_ticker or Polymarket event slug (e.g. `"KXBTC-25MAR14"`).
   */
  event_ticker?: string | null;
  /**
   * Source exchange. Options: `kalshi`, `polymarket`.
   */
  exchange: string;
  /**
   * Last trade price as YES probability in `[0, 1]` (e.g. `0.62`).
   */
  last_trade_price?: number | null;
  /**
   * Outcome shape. Options: `binary`, `categorical`, `scalar`.
   */
  market_type: MarketType;
  /**
   * Minimum order size in contracts (e.g. `1.0`).
   */
  min_order_size?: number | null;
  /**
   * Polymarket neg-risk flag; `null` on Kalshi.
   */
  neg_risk?: boolean | null;
  /**
   * Polymarket neg-risk market id; `null` on Kalshi.
   */
  neg_risk_market_id?: string | null;
  /**
   * Polymarket numeric DB id used for REST deep-links (e.g. `"1031769"`); `null` on Kalshi.
   */
  numeric_id?: string | null;
  /**
   * Market open time in UTC.
   */
  open_time?: string | null;
  /**
   * OpenPX primary key in `<exchange>:<ticker>` form (e.g. `"kalshi:KXBTCD-25APR1517"`).
   */
  openpx_id: string;
  /**
   * Ordered outcomes; binary markets have two (`"Yes"`, `"No"`), categorical have N.
   */
  outcomes?: Outcome[];
  /**
   * Winning outcome label after settlement (e.g. `"Yes"`); `null` until resolved.
   */
  result?: string | null;
  /**
   * Resolution rules in plain text; `null` when upstream omits them.
   */
  rules?: string | null;
  /**
   * Settlement time in UTC; `null` until the market resolves on-chain.
   */
  settlement_time?: string | null;
  /**
   * Lifecycle state. Options: `active`, `closed`, `resolved`.
   */
  status: MarketStatus;
  /**
   * Minimum price increment in dollars (e.g. `0.01`).
   */
  tick_size?: number | null;
  /**
   * Native ticker — Kalshi market ticker or Polymarket slug (e.g. `"KXBTCD-25APR1517"`).
   */
  ticker: string;
  /**
   * Human-readable market title (e.g. `"Will BTC close above $100k on Apr 15?"`).
   */
  title: string;
  /**
   * Lifetime trading volume in USD (e.g. `12345.67`).
   */
  volume: number;
  /**
   * 24-hour trading volume in USD; `null` when upstream omits it.
   */
  volume_24h?: number | null;
  [k: string]: unknown;
}
/**
 * One outcome of a prediction market.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Outcome".
 */
export interface Outcome {
  /**
   * Outcome label (e.g. `"Yes"`, `"No"`, or a categorical option name).
   */
  label: string;
  /**
   * Current price as YES probability in `[0, 1]` (e.g. `0.62`); `null` when not yet quoted.
   */
  price?: number | null;
  /**
   * Polymarket CTF token id used for per-outcome orderbook subscriptions; `null` on Kalshi.
   */
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * A market plus its parent event and series.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketLineage".
 */
export interface MarketLineage {
  /**
   * Parent event; `null` if the market is standalone or the parent is missing upstream.
   */
  event?: Event | null;
  /**
   * The market itself.
   */
  market: Market;
  /**
   * Parent series; `null` if the event is standalone or the parent is missing upstream.
   */
  series?: Series | null;
  [k: string]: unknown;
}
/**
 * A recurring family of events (e.g. a weekly inflation reading or sports season).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Series".
 */
export interface Series {
  /**
   * Topical category (e.g. `"Politics"`); `null` when upstream omits it.
   */
  category?: string | null;
  /**
   * Fee schedule label (e.g. `"flat"`); `null` when upstream omits it.
   */
  fee_type?: string | null;
  /**
   * Cadence string (e.g. `"weekly"`); `null` when upstream omits it.
   */
  frequency?: string | null;
  /**
   * Last upstream update time in UTC.
   */
  last_updated_ts?: string | null;
  /**
   * Polymarket numeric series id (e.g. `"10345"`); `null` on Kalshi.
   */
  numeric_id?: string | null;
  /**
   * Resolution sources used by the exchange (e.g. `[{"name": "BLS", "url": "..."}]`).
   */
  settlement_sources?: SettlementSource[];
  /**
   * Free-form tags (e.g. `["macro", "fed"]`).
   */
  tags?: string[];
  /**
   * Native series identifier — Kalshi series ticker or Polymarket series ticker/slug (e.g. `"KXPRES"`).
   */
  ticker: string;
  /**
   * Human-readable series title (e.g. `"US Presidential Election"`).
   */
  title: string;
  /**
   * Lifetime trading volume in USD across the series (e.g. `123456.78`).
   */
  volume?: number | null;
  [k: string]: unknown;
}
/**
 * Reference used by the exchange to settle a series.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SettlementSource".
 */
export interface SettlementSource {
  /**
   * Display name of the source (e.g. `"Bureau of Labor Statistics"`).
   */
  name?: string | null;
  /**
   * Source URL (e.g. `"https://www.bls.gov/cpi/"`).
   */
  url?: string | null;
  [k: string]: unknown;
}
/**
 * A public trade off the market tape.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketTrade".
 */
export interface MarketTrade {
  /**
   * Direction of the taker relative to YES. Options: `buy`, `sell`; `null` when unknown.
   */
  aggressor_side?: string | null;
  /**
   * Upstream trade time in UTC (e.g. `"2026-04-25T12:00:00Z"`).
   */
  exchange_ts: string;
  /**
   * Globally-unique exchange trade id (e.g. `"t-9c2..."`).
   */
  id: string;
  /**
   * NO-side reference price for binary markets (e.g. `0.38`).
   */
  no_price?: number | null;
  /**
   * Wall-clock time OpenPX served the trade (UTC).
   */
  openpx_ts: string;
  /**
   * Outcome label (e.g. `"Yes"`, `"No"`); `null` when not exposed.
   */
  outcome?: string | null;
  /**
   * Trade price as YES probability in `[0, 1]` (e.g. `0.62`).
   */
  price: number;
  /**
   * Filled size in contracts (e.g. `25.0`).
   */
  size: number;
  /**
   * Polymarket taker wallet address (e.g. `"0x..."`); `null` on Kalshi.
   */
  taker_address?: string | null;
  /**
   * YES-side reference price for binary markets (e.g. `0.62`).
   */
  yes_price?: number | null;
  [k: string]: unknown;
}
/**
 * Largest consecutive-level price gap per side.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MaxGap".
 */
export interface MaxGap {
  /**
   * Max ask-side gap in basis points (e.g. `25.0`).
   */
  ask_gap_bps?: number | null;
  /**
   * Max bid-side gap in basis points (e.g. `25.0`).
   */
  bid_gap_bps?: number | null;
  [k: string]: unknown;
}
/**
 * An order on the unified surface.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Order".
 */
export interface Order {
  /**
   * Order creation time (UTC) (e.g. `"2026-04-25T12:00:00Z"`).
   */
  created_at: string;
  /**
   * Volume-weighted per-contract fee in quote dollars; `null` on Polymarket and on unfilled orders.
   */
  fee?: number | null;
  /**
   * Cumulative filled size in contracts (e.g. `25.0`).
   */
  filled: number;
  /**
   * Globally-unique exchange order id (e.g. `"a1b2c3d4-..."`).
   */
  id: string;
  /**
   * Unified market ticker the order belongs to (e.g. `"KXBTCD-25APR1517"`).
   */
  market_ticker: string;
  /**
   * Outcome label as published by the exchange (e.g. `"Yes"`, `"No"`, or a categorical label).
   */
  outcome: string;
  /**
   * Limit price as YES probability in `(0, 1)` (e.g. `0.62`).
   */
  price: number;
  /**
   * Order direction. Options: `buy`, `sell`.
   */
  side: OrderSide;
  /**
   * Order size in contracts (e.g. `100.0`).
   */
  size: number;
  /**
   * Order lifecycle state. Options: `pending`, `open`, `filled`, `partially_filled`, `cancelled`, `rejected`.
   */
  status: OrderStatus;
  /**
   * Last update time (UTC); `null` if untouched since creation.
   */
  updated_at?: string | null;
  [k: string]: unknown;
}
/**
 * Full-depth L2 orderbook for one asset.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Orderbook".
 */
export interface Orderbook {
  /**
   * Ask levels, sorted ascending by price.
   */
  asks: PriceLevel[];
  /**
   * The orderable asset — Kalshi market ticker or Polymarket CTF token id (e.g. `"KXBTCD-25APR1517"`).
   */
  asset_id: string;
  /**
   * Bid levels, sorted descending by price.
   */
  bids: PriceLevel[];
  /**
   * Polymarket book-state hash for replay integrity; `null` on Kalshi.
   */
  hash?: string | null;
  /**
   * Monotonic sequence id from upstream; `null` when not provided.
   */
  last_update_id?: number | null;
  /**
   * Upstream snapshot time in UTC (e.g. `"2026-04-25T12:00:00Z"`).
   */
  timestamp?: string | null;
  [k: string]: unknown;
}
/**
 * A single resting orderbook level.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevel".
 */
export interface PriceLevel {
  /**
   * Price as YES probability in `[0, 1]` (e.g. `0.62`).
   */
  price: Number;
  /**
   * Resting size at this price in contracts (e.g. `100.0`).
   */
  size: number;
  [k: string]: unknown;
}
/**
 * Slippage curve at one requested size.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookImpact".
 */
export interface OrderbookImpact {
  /**
   * Orderable asset id (e.g. `"KXBTCD-25APR1517"`).
   */
  asset_id: string;
  /**
   * Average fill price hitting asks (e.g. `0.625`).
   */
  buy_avg_price?: number | null;
  /**
   * Buy-side fill percentage in `[0, 100]` (e.g. `100.0`).
   */
  buy_fill_pct: number;
  /**
   * Buy-side slippage vs mid in basis points (e.g. `80.0`).
   */
  buy_slippage_bps?: number | null;
  /**
   * Upstream snapshot time in UTC; `null` when not provided.
   */
  exchange_ts?: string | null;
  /**
   * Mid price as YES probability (e.g. `0.62`).
   */
  mid?: number | null;
  /**
   * Wall-clock time OpenPX served the response (UTC).
   */
  openpx_ts: string;
  /**
   * Average fill price hitting bids (e.g. `0.615`).
   */
  sell_avg_price?: number | null;
  /**
   * Sell-side fill percentage in `[0, 100]` (e.g. `100.0`).
   */
  sell_fill_pct: number;
  /**
   * Sell-side slippage vs mid in basis points (e.g. `80.0`).
   */
  sell_slippage_bps?: number | null;
  /**
   * Requested order size in contracts (e.g. `100.0`).
   */
  size: number;
  [k: string]: unknown;
}
/**
 * Microstructure signals for one orderbook.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookMicrostructure".
 */
export interface OrderbookMicrostructure {
  /**
   * OLS slope of cumulative ask size vs distance-from-mid (e.g. `12.5`).
   */
  ask_slope?: number | null;
  /**
   * Orderable asset id (e.g. `"KXBTCD-25APR1517"`).
   */
  asset_id: string;
  /**
   * OLS slope of cumulative bid size vs distance-from-mid (e.g. `12.5`).
   */
  bid_slope?: number | null;
  /**
   * Cumulative depth at 10/50/100 bps from mid.
   */
  depth_buckets: DepthBuckets;
  /**
   * Upstream snapshot time in UTC; `null` when not provided.
   */
  exchange_ts?: string | null;
  /**
   * Number of levels per side.
   */
  level_count: LevelCount;
  /**
   * Largest consecutive-level price gap on each side, in basis points.
   */
  max_gap: MaxGap;
  /**
   * Wall-clock time OpenPX served the response (UTC).
   */
  openpx_ts: string;
  [k: string]: unknown;
}
/**
 * Top-of-book snapshot stats for one asset.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookStats".
 */
export interface OrderbookStats {
  /**
   * Total resting ask size in contracts (e.g. `1000.0`).
   */
  ask_depth: number;
  /**
   * Orderable asset id (e.g. `"KXBTCD-25APR1517"`).
   */
  asset_id: string;
  /**
   * Best ask as YES probability (e.g. `0.63`).
   */
  best_ask?: number | null;
  /**
   * Best bid as YES probability (e.g. `0.61`).
   */
  best_bid?: number | null;
  /**
   * Total resting bid size in contracts (e.g. `1000.0`).
   */
  bid_depth: number;
  /**
   * Upstream snapshot time in UTC; `null` when not provided.
   */
  exchange_ts?: string | null;
  /**
   * Top-10 imbalance in `[-1, 1]` (positive = bid-heavy) (e.g. `0.12`).
   */
  imbalance?: number | null;
  /**
   * Mid price as YES probability (e.g. `0.62`).
   */
  mid?: number | null;
  /**
   * Wall-clock time OpenPX served the response (UTC).
   */
  openpx_ts: string;
  /**
   * Spread in basis points relative to mid (e.g. `400.0`).
   */
  spread_bps?: number | null;
  /**
   * Size-weighted mid using the top-10 levels (e.g. `0.62`).
   */
  weighted_mid?: number | null;
  [k: string]: unknown;
}
/**
 * An open position held by the caller.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Position".
 */
export interface Position {
  /**
   * Volume-weighted average entry price as YES probability in `[0, 1]` (e.g. `0.55`).
   */
  average_price: number;
  /**
   * Current mark price as YES probability in `[0, 1]` (e.g. `0.62`).
   */
  current_price: number;
  /**
   * Unified market ticker the position is held on (e.g. `"KXBTCD-25APR1517"`).
   */
  market_ticker: string;
  /**
   * Outcome label as published by the exchange (e.g. `"Yes"`, `"No"`).
   */
  outcome: string;
  /**
   * Number of contracts held (e.g. `100.0`).
   */
  size: number;
  [k: string]: unknown;
}
/**
 * One price-level update; `size > 0` sets the level, `size == 0` removes it.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevelChange".
 */
export interface PriceLevelChange {
  /**
   * Price as YES probability in `[0, 1]` (e.g. `0.62`).
   */
  price: Number;
  /**
   * Which side. Options: `bid`, `ask`.
   */
  side: PriceLevelSide;
  /**
   * New size at this price in contracts; `0` removes the level.
   */
  size: number;
  [k: string]: unknown;
}
/**
 * Real-time sports score/state from the Polymarket Sports WebSocket. Serializes as snake_case for end-users; aliases accept the upstream camelCase.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SportResult".
 */
export interface SportResult {
  away_team: string;
  elapsed?: string | null;
  ended: boolean;
  finished_timestamp?: string | null;
  game_id: number;
  home_team: string;
  league_abbreviation: string;
  live: boolean;
  period?: string | null;
  score?: string | null;
  slug: string;
  status: string;
  turn?: string | null;
  [k: string]: unknown;
}
/**
 * Request for `fetch_trades` — recent public trades ("tape") for one market.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "TradesRequest".
 */
export interface TradesRequest {
  /**
   * Market identifier — Kalshi market ticker or Polymarket Gamma slug (e.g. `"KXBTCD-25APR1517"`).
   */
  asset_id: string;
  /**
   * Opaque cursor returned by a prior page (e.g. `"eyJvIjoxMDB9"`).
   */
  cursor?: string | null;
  /**
   * Inclusive upper bound, unix seconds (e.g. `1714608000`).
   */
  end_ts?: number | null;
  /**
   * Max trades to return; capped at 1000 (Kalshi) / 500 (Polymarket) (e.g. `100`).
   */
  limit?: number | null;
  /**
   * Inclusive lower bound, unix seconds (e.g. `1714521600`).
   */
  start_ts?: number | null;
  [k: string]: unknown;
}
