/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "LiquidityRole".
 */
export type LiquidityRole = "maker" | "taker";
/**
 * Order time-in-force / execution type.
 *
 * Normalized across all exchanges: - `Gtc` (good-til-cancelled) — rests on the book until filled or cancelled. - `Ioc` (immediate-or-cancel) — fills what it can immediately, cancels the rest. - `Fok` (fill-or-kill) — must fill entirely in one shot or is cancelled.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderType".
 */
export type OrderType = "gtc" | "ioc" | "fok";
/**
 * Selects which outcome of a market an order targets.
 *
 * `Yes` / `No` cover binary markets on both exchanges. The remaining variants only resolve on Polymarket (multi-outcome categorical markets); Kalshi markets are always binary, so anything other than `Yes` / `No` is rejected with `InvalidInput` at the Kalshi adapter.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderOutcome".
 */
export type OrderOutcome =
  | "yes"
  | "no"
  | {
      label: string;
    }
  | {
      index: number;
    }
  | {
      token_id: string;
    };
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderSide".
 */
export type OrderSide = "buy" | "sell";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CryptoPriceSource".
 */
export type CryptoPriceSource = "binance" | "chainlink";
/**
 * Filter for market status in fetch queries.
 *
 * Unlike `MarketStatus` (which represents a market's actual status), this enum includes an `All` variant for fetching markets regardless of status.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketStatusFilter".
 */
export type MarketStatusFilter = "active" | "closed" | "resolved" | "all";
/**
 * Why a specific book was invalidated — handed to users so they can decide whether to alert, log, or handle it silently.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "InvalidationReason".
 */
export type InvalidationReason =
  | ("Reconnect" | "Lag" | "ExchangeReset")
  | {
      SequenceGap: {
        expected: number;
        received: number;
        [k: string]: unknown;
      };
    };
/**
 * Market type classification.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketType".
 */
export type MarketType = "binary" | "categorical" | "scalar";
/**
 * Normalized market status across all exchanges.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketStatus".
 */
export type MarketStatus = "active" | "closed" | "resolved";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = "pending" | "open" | "filled" | "partially_filled" | "cancelled" | "rejected";
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "number".
 */
export type Number = number;
/**
 * Bid or ask side. Serializes as "bid"/"ask" on the wire.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevelSide".
 */
export type PriceLevelSide = "bid" | "ask";
/**
 * Connection-level events, emitted on a channel separate from `WsUpdate` so a reconnect is observable as a single global signal rather than per-market.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SessionEvent".
 */
export type SessionEvent =
  | {
      kind: "Connected";
      [k: string]: unknown;
    }
  | {
      gap_ms: number;
      kind: "Reconnected";
      [k: string]: unknown;
    }
  | {
      dropped: number;
      first_seq: number;
      kind: "Lagged";
      last_seq: number;
      [k: string]: unknown;
    }
  | {
      kind: "BookInvalidated";
      market_id: string;
      reason: InvalidationReason;
      [k: string]: unknown;
    }
  | {
      kind: "Error";
      message: string;
      [k: string]: unknown;
    };
/**
 * Every per-market event the WebSocket surface emits. Closed tagged union; no untyped escape hatch in the stable enum. If an exchange grows a payload we want to surface in raw form, add a separate `raw_events()` stream rather than another `WsUpdate` variant — keeps consumer `match` exhaustiveness honest.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "WsUpdate".
 */
export type WsUpdate =
  | {
      asset_id: string;
      book: Orderbook;
      exchange_ts?: number | null;
      kind: "Snapshot";
      local_ts_ms: number;
      market_id: string;
      seq: number;
      [k: string]: unknown;
    }
  | {
      asset_id: string;
      changes: PriceLevelChange[];
      exchange_ts?: number | null;
      kind: "Delta";
      local_ts_ms: number;
      market_id: string;
      seq: number;
      [k: string]: unknown;
    }
  | {
      asset_id: string;
      kind: "Clear";
      local_ts_ms: number;
      market_id: string;
      reason: InvalidationReason;
      seq: number;
      [k: string]: unknown;
    }
  | {
      kind: "Trade";
      local_ts_ms: number;
      trade: ActivityTrade;
      [k: string]: unknown;
    }
  | {
      fill: ActivityFill;
      kind: "Fill";
      local_ts_ms: number;
      [k: string]: unknown;
    };

/**
 * Auto-generated JSON Schema for OpenPX core types
 */
export interface OpenPX {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ActivityFill".
 */
export interface ActivityFill {
  asset_id: string;
  /**
   * Exchange-authoritative timestamp (millis since epoch).
   */
  exchange_ts_ms?: number | null;
  /**
   * Fee charged for this fill, when the exchange publishes one.
   */
  fee?: number | null;
  fill_id?: string | null;
  liquidity_role?: LiquidityRole | null;
  market_id: string;
  order_id?: string | null;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  /**
   * On-chain transaction hash, when the exchange publishes one.
   */
  tx_hash?: string | null;
  [k: string]: unknown;
}
/**
 * Activity events still carried inside `WsUpdate::Trade` / `WsUpdate::Fill`. Retained as a typed payload alongside the stream rather than as a separate per-token surface.
 *
 * `exchange_ts_ms` is exchange-authoritative millis since epoch — uniform with `WsUpdate::{Snapshot, Delta}::exchange_ts`, so every timestamp on the WS surface is the same type (`u64` millis). `chrono::DateTime` was more expressive but cost a representation mismatch at every FFI boundary.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ActivityTrade".
 */
export interface ActivityTrade {
  aggressor_side?: string | null;
  asset_id: string;
  /**
   * Exchange-authoritative timestamp (millis since epoch).
   */
  exchange_ts_ms?: number | null;
  /**
   * Fee rate in basis points (e.g. 0 = no fee, 200 = 2%). Polymarket `last_trade_price` events populate this.
   */
  fee_rate_bps?: number | null;
  market_id: string;
  outcome?: string | null;
  price: number;
  side?: string | null;
  size: number;
  source_channel: string;
  trade_id?: string | null;
  [k: string]: unknown;
}
/**
 * Lean input shape for `Exchange::create_order`. All cross-venue and per-venue knobs are deliberately absent — `post_only`, `expiration_ts`, `client_order_id`, `reduce_only`, `neg_risk`, builder/metadata, and subaccounts are not exposed. Anything an exchange requires that is not modelled here is generated internally (e.g. Kalshi V2's required `client_order_id` is filled with a per-call UUID).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CreateOrderRequest".
 */
export interface CreateOrderRequest {
  /**
   * Unified market identifier — Kalshi market ticker or Polymarket slug.
   */
  market_ticker: string;
  /**
   * Time-in-force / execution type.
   */
  order_type?: OrderType & string;
  /**
   * Which outcome of the market to trade.
   */
  outcome: OrderOutcome;
  /**
   * Limit price as YES probability in `(0.0, 1.0)`.
   */
  price: number;
  /**
   * Buy or sell.
   */
  side: OrderSide;
  /**
   * Order size in contracts.
   */
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "CryptoPrice".
 */
export interface CryptoPrice {
  source: CryptoPriceSource;
  symbol: string;
  timestamp: number;
  value: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "DepthBuckets".
 */
export interface DepthBuckets {
  ask_within_100bps: number;
  ask_within_10bps: number;
  ask_within_50bps: number;
  bid_within_100bps: number;
  bid_within_10bps: number;
  bid_within_50bps: number;
  [k: string]: unknown;
}
/**
 * A grouping of related markets. On Kalshi, an Event is a single resolution (e.g. "Will Candidate X win State Y?") with one or more contracts. On Polymarket, an Event is the parent of one or more Markets sharing a common theme (e.g. "2028 US Presidential Election" with markets per candidate).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  category?: string | null;
  description?: string | null;
  end_ts?: string | null;
  last_updated_ts?: string | null;
  /**
   * Sibling market market_tickers under this event — unified `Market.ticker` values (Kalshi market market_tickers; Polymarket slugs).
   */
  market_tickers?: string[];
  mutually_exclusive?: boolean | null;
  /**
   * Polymarket's numeric REST id for the event (e.g. `"12585"`). None on Kalshi (no separate numeric event surface).
   */
  numeric_id?: string | null;
  open_interest?: number | null;
  /**
   * Parent series ticker. Kalshi: upstream `series_ticker`. Polymarket: the embedded series's `ticker` (or `slug` if `ticker` is null).
   */
  series_ticker?: string | null;
  start_ts?: string | null;
  status?: string | null;
  /**
   * Native event identifier. Kalshi: `event_ticker` (e.g. `"KXPRES-2028"`). Polymarket: the event slug (e.g. `"presidential-election-winner-2024"`).
   */
  ticker: string;
  title: string;
  volume?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "ExchangeInfo".
 */
export interface ExchangeInfo {
  has_approvals: boolean;
  has_cancel_all_orders: boolean;
  has_cancel_order: boolean;
  has_create_order: boolean;
  has_create_orders_batch: boolean;
  has_fetch_balance: boolean;
  has_fetch_fills: boolean;
  has_fetch_market_lineage: boolean;
  has_fetch_markets: boolean;
  has_fetch_orderbook: boolean;
  has_fetch_orderbooks_batch: boolean;
  has_fetch_positions: boolean;
  has_fetch_server_time: boolean;
  has_fetch_trades: boolean;
  has_refresh_balance: boolean;
  has_websocket: boolean;
  id: string;
  name: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "FetchMarketsParams".
 */
export interface FetchMarketsParams {
  /**
   * Exchange-specific cursor (offset, page number, or cursor string)
   */
  cursor?: string | null;
  /**
   * Fetch all markets within a specific event. Pass a Kalshi event ticker (e.g., `"KXBTC-25MAR14"`) or a Polymarket event slug (e.g., `"will-trump-win-2024"`). Polymarket numeric event IDs are not accepted — they will be supported via a future `event_numeric_id` field. When set, `cursor` and `limit` are ignored (not paginated). `status` filtering is still applied client-side.
   */
  event_ticker?: string | null;
  /**
   * Per-page limit. Each exchange applies its own server-side cap: Kalshi tops out at 1000, Polymarket at ~500. Values above the cap are silently clamped to the cap.
   */
  limit?: number | null;
  /**
   * Fetch a specific set of markets by their unified ticker. Each entry is a Kalshi market ticker (e.g., `"KXBTCD-25APR1517"`) or a Polymarket market slug (e.g., `"will-trump-win-2024"`). When non-empty, `cursor`, `event_ticker`, and `series_ticker` are ignored.
   */
  market_tickers?: string[];
  /**
   * Filter by series ticker. Pass a Kalshi series ticker (e.g., `"KXBTC"`) to fetch only markets in that series. Polymarket support arrives once `series_numeric_id` is added to this struct — until then, this field is ignored on Polymarket.
   */
  series_ticker?: string | null;
  /**
   * Filter by market status. Defaults to Active at the exchange level when None. Use `MarketStatusFilter::All` to fetch markets of any status.
   */
  status?: MarketStatusFilter | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "FetchOrdersParams".
 */
export interface FetchOrdersParams {
  market_ticker?: string | null;
  [k: string]: unknown;
}
/**
 * A single fill (trade execution) from a user's order.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Fill".
 */
export interface Fill {
  created_at: string;
  fee: number;
  fill_id: string;
  is_taker: boolean;
  market_ticker: string;
  order_id: string;
  outcome: string;
  price: number;
  side: OrderSide;
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "LevelCount".
 */
export interface LevelCount {
  asks: number;
  bids: number;
  [k: string]: unknown;
}
/**
 * Unified prediction market model.
 *
 * All exchanges produce this single type directly — no intermediate conversion.
 *
 * # Price Format
 *
 * All prices are normalized to decimal format (0.0 to 1.0). Exchange-specific conversions are handled during parsing:
 *
 * - **Kalshi**: Fixed-point dollar strings parsed directly (post March 2026 migration). - **Polymarket**: Native prices already in decimal (0.0-1.0).
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Market".
 */
export interface Market {
  /**
   * Best ask price (normalized 0-1)
   */
  best_ask?: number | null;
  /**
   * Best bid price (normalized 0-1)
   */
  best_bid?: number | null;
  /**
   * Market close time
   */
  close_time?: string | null;
  /**
   * Polymarket CTF condition id
   */
  condition_id?: string | null;
  /**
   * Market creation time
   */
  created_at?: string | null;
  /**
   * Native event identifier this market belongs to. Kalshi: upstream `event_ticker`. Polymarket: the parent event's `slug`.
   */
  event_ticker?: string | null;
  /**
   * Exchange identifier (kalshi, polymarket)
   */
  exchange: string;
  /**
   * Last trade price (normalized 0-1)
   */
  last_trade_price?: number | null;
  /**
   * Market type classification
   */
  market_type: MarketType;
  /**
   * Minimum order size (contracts). Kalshi: synthesized — 1.0, or 0.01 when fractional_trading_enabled. Polymarket: read directly from `orderMinSize`.
   */
  min_order_size?: number | null;
  /**
   * Polymarket: neg-risk flag
   */
  neg_risk?: boolean | null;
  /**
   * Polymarket: neg-risk market ID
   */
  neg_risk_market_id?: string | null;
  /**
   * Polymarket's numeric DB id (e.g. "1031769"). Exposed for callers that need to build UI deep-links or cross-reference Polymarket's REST-only numeric surface. Not used for trading or subscription.
   */
  numeric_id?: string | null;
  /**
   * Market open time
   */
  open_time?: string | null;
  /**
   * Primary key: {exchange}:{ticker}
   */
  openpx_id: string;
  /**
   * Ordered list of outcomes. Each entry carries label, price, and (if exposed) token id. Polymarket categorical markets have N entries; Kalshi binary markets always have 2 ("Yes" / "No").
   */
  outcomes?: Outcome[];
  /**
   * Resolution result. Kalshi: enum string from upstream. Polymarket: derived winning-outcome label (the `outcomes[i]` whose `outcomePrices[i]` is 1.0 after settlement). None for unresolved markets.
   */
  result?: string | null;
  /**
   * Resolution rules. Kalshi: `{rules_primary} | {rules_secondary}`. Polymarket: `description`.
   */
  rules?: string | null;
  /**
   * Settlement / resolution time. Kalshi: `settlement_ts`. Polymarket: `closedTime` (populated only after on-chain settlement).
   */
  settlement_time?: string | null;
  /**
   * Normalized status: Active, Closed, Resolved
   */
  status: MarketStatus;
  /**
   * Minimum price increment in dollars. Polymarket: `orderPriceMinTickSize` directly. Kalshi: the smallest `step` across the tiered `price_ranges` array (the finest precision the market accepts anywhere on its price curve — orders in coarser tiers must still round to that tier's step).
   */
  tick_size?: number | null;
  /**
   * Native exchange ticker. Kalshi: `ticker`. Polymarket: `slug`.
   */
  ticker: string;
  /**
   * Market title
   */
  title: string;
  /**
   * Total volume (USD)
   */
  volume: number;
  /**
   * 24-hour trading volume (USD)
   */
  volume_24h?: number | null;
  [k: string]: unknown;
}
/**
 * One outcome of a prediction market — label, current price, and (where the exchange exposes one) the on-chain token id needed to subscribe to its orderbook stream. Replaces the previous trio of `outcome_prices` map + `outcome_tokens` vec + binary-only `token_id_yes`/`token_id_no` with a single ordered list keyed by index.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Outcome".
 */
export interface Outcome {
  /**
   * Outcome label (e.g. "Yes", "No", or a categorical option name).
   */
  label: string;
  /**
   * Current outcome price in [0.0, 1.0]. None when not exposed (e.g. Kalshi markets pre-fill, or Polymarket categorical markets without a price).
   */
  price?: number | null;
  /**
   * CTF token id (Polymarket only). Used to subscribe to per-outcome orderbook streams. None on Kalshi.
   */
  token_id?: string | null;
  [k: string]: unknown;
}
/**
 * A market plus the parent event and series that contextualize it.
 *
 * `event` and `series` are `Option` because: - some markets have no parent event surface (Kalshi standalone markets); - the upstream lookup for the parent may legitimately 404 on a dangling reference. A dangling parent should not fail the whole call — the caller still gets the `Market`.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketLineage".
 */
export interface MarketLineage {
  event?: Event | null;
  market: Market;
  series?: Series | null;
  [k: string]: unknown;
}
/**
 * A recurring family of events. Examples: a weekly inflation reading, a monthly nonfarm payrolls release, a regular sports season. On Kalshi, a Series is identified by `series_ticker` (e.g. `KXPRES`). On Polymarket, a Series wraps multiple Events with shared metadata.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Series".
 */
export interface Series {
  category?: string | null;
  fee_type?: string | null;
  frequency?: string | null;
  last_updated_ts?: string | null;
  /**
   * Polymarket's numeric REST id for the series (e.g. `"10345"`). None on Kalshi (no separate numeric series surface).
   */
  numeric_id?: string | null;
  settlement_sources?: SettlementSource[];
  tags?: string[];
  /**
   * Native series identifier. Kalshi: `ticker` (e.g. `"KXPRES"`). Polymarket: the series's `ticker` field, falling back to `slug` when `ticker` is null upstream.
   */
  ticker: string;
  title: string;
  volume?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SettlementSource".
 */
export interface SettlementSource {
  name?: string | null;
  url?: string | null;
  [k: string]: unknown;
}
/**
 * Normalized public market trade, suitable for "tape" UIs.
 *
 * - `price` is normalized to [0.0, 1.0]; anchored to the Yes side on binary markets — use `no_price` for the No-side reference. - `aggressor_side` is "buy" / "sell" relative to the Yes side on binary markets — "buy" means upward pressure on Yes, "sell" downward. - `exchange_ts` is the upstream-provided trade timestamp. - `openpx_ts` is wall-clock when OpenPX served the response.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MarketTrade".
 */
export interface MarketTrade {
  aggressor_side?: string | null;
  exchange_ts: string;
  id: string;
  no_price?: number | null;
  openpx_ts: string;
  outcome?: string | null;
  price: number;
  size: number;
  taker_address?: string | null;
  yes_price?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "MaxGap".
 */
export interface MaxGap {
  ask_gap_bps?: number | null;
  bid_gap_bps?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Order".
 */
export interface Order {
  created_at: string;
  /**
   * Volume-weighted per-contract fee paid for fills resulting from this order, in quote-currency dollars. Kalshi reports it on `create_order` when fills occur immediately; Polymarket charges fees at trade settlement, so this stays `None` on initial create response.
   */
  fee?: number | null;
  filled: number;
  id: string;
  market_ticker: string;
  outcome: string;
  price: number;
  side: OrderSide;
  size: number;
  status: OrderStatus;
  updated_at?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Orderbook".
 */
export interface Orderbook {
  asks: PriceLevel[];
  asset_id: string;
  bids: PriceLevel[];
  /**
   * Exchange-provided hash for verifying book state integrity during replay. Polymarket: present on `book` snapshot events.
   */
  hash?: string | null;
  last_update_id?: number | null;
  timestamp?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevel".
 */
export interface PriceLevel {
  price: Number;
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookImpact".
 */
export interface OrderbookImpact {
  asset_id: string;
  buy_avg_price?: number | null;
  buy_fill_pct: number;
  buy_slippage_bps?: number | null;
  exchange_ts?: string | null;
  mid?: number | null;
  openpx_ts: string;
  sell_avg_price?: number | null;
  sell_fill_pct: number;
  sell_slippage_bps?: number | null;
  size: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookMicrostructure".
 */
export interface OrderbookMicrostructure {
  ask_slope?: number | null;
  asset_id: string;
  bid_slope?: number | null;
  depth_buckets: DepthBuckets;
  exchange_ts?: string | null;
  level_count: LevelCount;
  max_gap: MaxGap;
  openpx_ts: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "OrderbookStats".
 */
export interface OrderbookStats {
  ask_depth: number;
  asset_id: string;
  best_ask?: number | null;
  best_bid?: number | null;
  bid_depth: number;
  exchange_ts?: string | null;
  imbalance?: number | null;
  mid?: number | null;
  openpx_ts: string;
  spread_bps?: number | null;
  weighted_mid?: number | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "Position".
 */
export interface Position {
  average_price: number;
  current_price: number;
  market_ticker: string;
  outcome: string;
  size: number;
  [k: string]: unknown;
}
/**
 * A single price level change. Absolute replacement semantics: size > 0 = set level to this size, size == 0 = remove level.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "PriceLevelChange".
 */
export interface PriceLevelChange {
  price: Number;
  side: PriceLevelSide;
  size: number;
  [k: string]: unknown;
}
/**
 * Real-time sports score/state from the Polymarket Sports WebSocket. Serializes as snake_case for end-users; aliases accept the upstream camelCase.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "SportResult".
 */
export interface SportResult {
  away_team: string;
  elapsed?: string | null;
  ended: boolean;
  finished_timestamp?: string | null;
  game_id: number;
  home_team: string;
  league_abbreviation: string;
  live: boolean;
  period?: string | null;
  score?: string | null;
  slug: string;
  status: string;
  turn?: string | null;
  [k: string]: unknown;
}
/**
 * Request for fetching recent public trades ("tape") for a market.
 *
 * `asset_id` is the market identifier — Kalshi market ticker or Polymarket Gamma slug. Both Yes and No outcomes' trades are returned interleaved; use `MarketTrade.outcome` to distinguish.
 *
 * This interface was referenced by `OpenPX`'s JSON-Schema
 * via the `definition` "TradesRequest".
 */
export interface TradesRequest {
  asset_id: string;
  /**
   * Opaque cursor from a prior response.
   */
  cursor?: string | null;
  /**
   * Unix seconds (inclusive upper bound).
   */
  end_ts?: number | null;
  /**
   * Max trades to return. Capped per exchange (Kalshi 1000, Polymarket 500).
   */
  limit?: number | null;
  /**
   * Unix seconds (inclusive lower bound).
   */
  start_ts?: number | null;
  [k: string]: unknown;
}
