# generated by datamodel-codegen:
#   filename:  openpx.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, conint


class OpenPX(RootModel[Any]):
    root: Any = Field(
        ...,
        description="Auto-generated JSON Schema for OpenPX core types",
        title="OpenPX",
    )


class ActivityTrade(BaseModel):
    aggressor_side: str | None = None
    asset_id: str
    exchange_ts_ms: conint(ge=0) | None = Field(
        None, description="Exchange-authoritative timestamp (millis since epoch)."
    )
    fee_rate_bps: conint(ge=0) | None = Field(
        None,
        description="Fee rate in basis points (e.g. 0 = no fee, 200 = 2%). Polymarket `last_trade_price` events populate this.",
    )
    market_id: str
    outcome: str | None = None
    price: float
    side: str | None = None
    size: float
    source_channel: str
    trade_id: str | None = None


class CryptoPriceSource(Enum):
    binance = "binance"
    chainlink = "chainlink"


class DepthBuckets(BaseModel):
    ask_within_100bps: float
    ask_within_10bps: float
    ask_within_50bps: float
    bid_within_100bps: float
    bid_within_10bps: float
    bid_within_50bps: float


class Event(BaseModel):
    category: str | None = None
    description: str | None = None
    end_ts: AwareDatetime | None = None
    last_updated_ts: AwareDatetime | None = None
    market_tickers: list[str] | None = Field(
        [],
        description="Sibling market market_tickers under this event — unified `Market.ticker` values (Kalshi market market_tickers; Polymarket slugs).",
    )
    mutually_exclusive: bool | None = None
    numeric_id: str | None = Field(
        None,
        description='Polymarket\'s numeric REST id for the event (e.g. `"12585"`). None on Kalshi (no separate numeric event surface).',
    )
    open_interest: float | None = None
    series_ticker: str | None = Field(
        None,
        description="Parent series ticker. Kalshi: upstream `series_ticker`. Polymarket: the embedded series's `ticker` (or `slug` if `ticker` is null).",
    )
    start_ts: AwareDatetime | None = None
    status: str | None = None
    ticker: str = Field(
        ...,
        description='Native event identifier. Kalshi: `event_ticker` (e.g. `"KXPRES-2028"`). Polymarket: the event slug (e.g. `"presidential-election-winner-2024"`).',
    )
    title: str
    volume: float | None = None


class ExchangeInfo(BaseModel):
    has_approvals: bool
    has_cancel_all_orders: bool
    has_cancel_order: bool
    has_create_order: bool
    has_create_orders_batch: bool
    has_fetch_balance: bool
    has_fetch_fills: bool
    has_fetch_market_lineage: bool
    has_fetch_markets: bool
    has_fetch_orderbook: bool
    has_fetch_orderbooks_batch: bool
    has_fetch_positions: bool
    has_fetch_server_time: bool
    has_fetch_trades: bool
    has_refresh_balance: bool
    has_websocket: bool
    id: str
    name: str


class FetchOrdersParams(BaseModel):
    market_ticker: str | None = None


class InvalidationReason1(Enum):
    Reconnect = "Reconnect"
    Lag = "Lag"
    ExchangeReset = "ExchangeReset"


class SequenceGap(BaseModel):
    expected: conint(ge=0)
    received: conint(ge=0)


class InvalidationReason2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    SequenceGap_1: SequenceGap = Field(..., alias="SequenceGap")


class InvalidationReason(RootModel[InvalidationReason1 | InvalidationReason2]):
    root: InvalidationReason1 | InvalidationReason2 = Field(
        ...,
        description="Why a specific book was invalidated — handed to users so they can decide whether to alert, log, or handle it silently.",
    )


class LevelCount(BaseModel):
    asks: conint(ge=0)
    bids: conint(ge=0)


class LiquidityRole(Enum):
    maker = "maker"
    taker = "taker"


class MarketStatus(Enum):
    active = "active"
    closed = "closed"
    resolved = "resolved"


class MarketStatusFilter(Enum):
    active = "active"
    closed = "closed"
    resolved = "resolved"
    all = "all"


class MarketTrade(BaseModel):
    aggressor_side: str | None = None
    exchange_ts: AwareDatetime
    id: str
    no_price: float | None = None
    openpx_ts: AwareDatetime
    outcome: str | None = None
    price: float
    size: float
    taker_address: str | None = None
    yes_price: float | None = None


class MarketType(Enum):
    binary = "binary"
    categorical = "categorical"
    scalar = "scalar"


class MaxGap(BaseModel):
    ask_gap_bps: float | None = None
    bid_gap_bps: float | None = None


class OrderOutcome1(Enum):
    yes = "yes"


class OrderOutcome2(Enum):
    no = "no"


class OrderOutcome3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: str


class OrderOutcome(RootModel[OrderOutcome1 | OrderOutcome2 | OrderOutcome3]):
    root: OrderOutcome1 | OrderOutcome2 | OrderOutcome3 = Field(
        ...,
        description="Which outcome an order targets.\n\nOn Kalshi the value is load-bearing — `Yes` / `No` drives YES-frame bid/ask side selection and price mirroring at the V2 wire. Anything other than `Yes` / `No` is rejected with `InvalidInput`.\n\nOn Polymarket the order's outcome is encoded in `CreateOrderRequest.asset_id` (the per-outcome CTF token id), so this field is a response-label hint only — it shows up on `Order.outcome` but does not route the trade.",
        title="OrderOutcome",
    )


class OrderSide(Enum):
    buy = "buy"
    sell = "sell"


class OrderStatus(Enum):
    pending = "pending"
    open = "open"
    filled = "filled"
    partially_filled = "partially_filled"
    cancelled = "cancelled"
    rejected = "rejected"


class OrderType(Enum):
    gtc = "gtc"
    ioc = "ioc"
    fok = "fok"


class OrderbookImpact(BaseModel):
    asset_id: str
    buy_avg_price: float | None = None
    buy_fill_pct: float
    buy_slippage_bps: float | None = None
    exchange_ts: AwareDatetime | None = None
    mid: float | None = None
    openpx_ts: AwareDatetime
    sell_avg_price: float | None = None
    sell_fill_pct: float
    sell_slippage_bps: float | None = None
    size: float


class OrderbookMicrostructure(BaseModel):
    ask_slope: float | None = None
    asset_id: str
    bid_slope: float | None = None
    depth_buckets: DepthBuckets
    exchange_ts: AwareDatetime | None = None
    level_count: LevelCount
    max_gap: MaxGap
    openpx_ts: AwareDatetime


class OrderbookStats(BaseModel):
    ask_depth: float
    asset_id: str
    best_ask: float | None = None
    best_bid: float | None = None
    bid_depth: float
    exchange_ts: AwareDatetime | None = None
    imbalance: float | None = None
    mid: float | None = None
    openpx_ts: AwareDatetime
    spread_bps: float | None = None
    weighted_mid: float | None = None


class Outcome(BaseModel):
    label: str = Field(
        ...,
        description='Outcome label (e.g. "Yes", "No", or a categorical option name).',
    )
    price: float | None = Field(
        None,
        description="Current outcome price in [0.0, 1.0]. None when not exposed (e.g. Kalshi markets pre-fill, or Polymarket categorical markets without a price).",
    )
    token_id: str | None = Field(
        None,
        description="CTF token id (Polymarket only). Used to subscribe to per-outcome orderbook streams. None on Kalshi.",
    )


class Position(BaseModel):
    average_price: float
    current_price: float
    market_ticker: str
    outcome: str
    size: float


class PriceLevelSide(Enum):
    bid = "bid"
    ask = "ask"


class Kind(Enum):
    Connected = "Connected"


class SessionEvent1(BaseModel):
    kind: Kind


class Kind1(Enum):
    Reconnected = "Reconnected"


class SessionEvent2(BaseModel):
    gap_ms: conint(ge=0)
    kind: Kind1


class Kind2(Enum):
    Lagged = "Lagged"


class SessionEvent3(BaseModel):
    dropped: conint(ge=0)
    first_seq: conint(ge=0)
    kind: Kind2
    last_seq: conint(ge=0)


class Kind3(Enum):
    BookInvalidated = "BookInvalidated"


class SessionEvent4(BaseModel):
    kind: Kind3
    market_id: str
    reason: InvalidationReason


class Kind4(Enum):
    Error = "Error"


class SessionEvent5(BaseModel):
    kind: Kind4
    message: str


class SessionEvent(
    RootModel[
        SessionEvent1 | SessionEvent2 | SessionEvent3 | SessionEvent4 | SessionEvent5
    ]
):
    root: (
        SessionEvent1 | SessionEvent2 | SessionEvent3 | SessionEvent4 | SessionEvent5
    ) = Field(
        ...,
        description="Connection-level events, emitted on a channel separate from `WsUpdate` so a reconnect is observable as a single global signal rather than per-market.",
        title="SessionEvent",
    )


class SettlementSource(BaseModel):
    name: str | None = None
    url: str | None = None


class SportResult(BaseModel):
    away_team: str
    elapsed: str | None = None
    ended: bool
    finished_timestamp: AwareDatetime | None = None
    game_id: conint(ge=0)
    home_team: str
    league_abbreviation: str
    live: bool
    period: str | None = None
    score: str | None = None
    slug: str
    status: str
    turn: str | None = None


class TradesRequest(BaseModel):
    asset_id: str
    cursor: str | None = Field(None, description="Opaque cursor from a prior response.")
    end_ts: int | None = Field(
        None, description="Unix seconds (inclusive upper bound)."
    )
    limit: conint(ge=0) | None = Field(
        None,
        description="Max trades to return. Capped per exchange (Kalshi 1000, Polymarket 500).",
    )
    start_ts: int | None = Field(
        None, description="Unix seconds (inclusive lower bound)."
    )


class Kind5(Enum):
    Snapshot = "Snapshot"


class Kind6(Enum):
    Delta = "Delta"


class Kind7(Enum):
    Clear = "Clear"


class WsUpdate3(BaseModel):
    asset_id: str
    kind: Kind7
    local_ts_ms: conint(ge=0)
    market_id: str
    reason: InvalidationReason
    seq: conint(ge=0)


class Kind8(Enum):
    Trade = "Trade"


class WsUpdate4(BaseModel):
    kind: Kind8
    local_ts_ms: conint(ge=0)
    trade: ActivityTrade


class Kind9(Enum):
    Fill = "Fill"


class Number(RootModel[float]):
    root: float


class ActivityFill(BaseModel):
    asset_id: str
    exchange_ts_ms: conint(ge=0) | None = Field(
        None, description="Exchange-authoritative timestamp (millis since epoch)."
    )
    fee: float | None = Field(
        None, description="Fee charged for this fill, when the exchange publishes one."
    )
    fill_id: str | None = None
    liquidity_role: LiquidityRole | None = None
    market_id: str
    order_id: str | None = None
    outcome: str | None = None
    price: float
    side: str | None = None
    size: float
    source_channel: str
    tx_hash: str | None = Field(
        None, description="On-chain transaction hash, when the exchange publishes one."
    )


class CreateOrderRequest(BaseModel):
    asset_id: str = Field(
        ...,
        description="Per-outcome asset identifier — Kalshi market ticker, Polymarket CTF token id. Same convention as `Exchange::fetch_orderbook` — the value identifies the orderable thing (a Kalshi market is orderable as a whole; a Polymarket order targets one CTF token). Polymarket callers who hold a slug + outcome label must resolve the token id themselves via `fetch_market` before submitting.",
    )
    order_type: OrderType | None = Field(
        "gtc", description="Time-in-force / execution type."
    )
    outcome: OrderOutcome = Field(
        ...,
        description="On Kalshi, drives YES-frame bid/ask side selection — required. On Polymarket, response-label hint only (the actual outcome is encoded in `asset_id`).",
    )
    price: float = Field(
        ..., description="Limit price as YES probability in `(0.0, 1.0)`."
    )
    side: OrderSide = Field(..., description="Buy or sell.")
    size: float = Field(..., description="Order size in contracts.")


class CryptoPrice(BaseModel):
    source: CryptoPriceSource
    symbol: str
    timestamp: conint(ge=0)
    value: float


class FetchMarketsParams(BaseModel):
    cursor: str | None = Field(
        None,
        description="Exchange-specific cursor (offset, page number, or cursor string)",
    )
    event_ticker: str | None = Field(
        None,
        description='Fetch all markets within a specific event. Pass a Kalshi event ticker (e.g., `"KXBTC-25MAR14"`) or a Polymarket event slug (e.g., `"will-trump-win-2024"`). Polymarket numeric event IDs are not accepted — they will be supported via a future `event_numeric_id` field. When set, `cursor` and `limit` are ignored (not paginated). `status` filtering is still applied client-side.',
    )
    limit: conint(ge=0) | None = Field(
        None,
        description="Per-page limit. Each exchange applies its own server-side cap: Kalshi tops out at 1000, Polymarket at ~500. Values above the cap are silently clamped to the cap.",
    )
    market_tickers: list[str] | None = Field(
        [],
        description='Fetch a specific set of markets by their unified ticker. Each entry is a Kalshi market ticker (e.g., `"KXBTCD-25APR1517"`) or a Polymarket market slug (e.g., `"will-trump-win-2024"`). When non-empty, `cursor`, `event_ticker`, and `series_ticker` are ignored.',
    )
    series_ticker: str | None = Field(
        None,
        description='Filter by series ticker. Pass a Kalshi series ticker (e.g., `"KXBTC"`) to fetch only markets in that series. Polymarket support arrives once `series_numeric_id` is added to this struct — until then, this field is ignored on Polymarket.',
    )
    status: MarketStatusFilter | None = Field(
        None,
        description="Filter by market status. Defaults to Active at the exchange level when None. Use `MarketStatusFilter::All` to fetch markets of any status.",
    )


class Fill(BaseModel):
    created_at: AwareDatetime
    fee: float
    fill_id: str
    is_taker: bool
    market_ticker: str
    order_id: str
    outcome: str
    price: float
    side: OrderSide
    size: float


class Market(BaseModel):
    best_ask: float | None = Field(None, description="Best ask price (normalized 0-1)")
    best_bid: float | None = Field(None, description="Best bid price (normalized 0-1)")
    close_time: AwareDatetime | None = Field(None, description="Market close time")
    condition_id: str | None = Field(None, description="Polymarket CTF condition id")
    created_at: AwareDatetime | None = Field(None, description="Market creation time")
    event_ticker: str | None = Field(
        None,
        description="Native event identifier this market belongs to. Kalshi: upstream `event_ticker`. Polymarket: the parent event's `slug`.",
    )
    exchange: str = Field(..., description="Exchange identifier (kalshi, polymarket)")
    last_trade_price: float | None = Field(
        None, description="Last trade price (normalized 0-1)"
    )
    market_type: MarketType = Field(..., description="Market type classification")
    min_order_size: float | None = Field(
        None,
        description="Minimum order size (contracts). Kalshi: synthesized — 1.0, or 0.01 when fractional_trading_enabled. Polymarket: read directly from `orderMinSize`.",
    )
    neg_risk: bool | None = Field(None, description="Polymarket: neg-risk flag")
    neg_risk_market_id: str | None = Field(
        None, description="Polymarket: neg-risk market ID"
    )
    numeric_id: str | None = Field(
        None,
        description="Polymarket's numeric DB id (e.g. \"1031769\"). Exposed for callers that need to build UI deep-links or cross-reference Polymarket's REST-only numeric surface. Not used for trading or subscription.",
    )
    open_time: AwareDatetime | None = Field(None, description="Market open time")
    openpx_id: str = Field(..., description="Primary key: {exchange}:{ticker}")
    outcomes: list[Outcome] | None = Field(
        [],
        description='Ordered list of outcomes. Each entry carries label, price, and (if exposed) token id. Polymarket categorical markets have N entries; Kalshi binary markets always have 2 ("Yes" / "No").',
        validate_default=True,
    )
    result: str | None = Field(
        None,
        description="Resolution result. Kalshi: enum string from upstream. Polymarket: derived winning-outcome label (the `outcomes[i]` whose `outcomePrices[i]` is 1.0 after settlement). None for unresolved markets.",
    )
    rules: str | None = Field(
        None,
        description="Resolution rules. Kalshi: `{rules_primary} | {rules_secondary}`. Polymarket: `description`.",
    )
    settlement_time: AwareDatetime | None = Field(
        None,
        description="Settlement / resolution time. Kalshi: `settlement_ts`. Polymarket: `closedTime` (populated only after on-chain settlement).",
    )
    status: MarketStatus = Field(
        ..., description="Normalized status: Active, Closed, Resolved"
    )
    tick_size: float | None = Field(
        None,
        description="Minimum price increment in dollars. Polymarket: `orderPriceMinTickSize` directly. Kalshi: the smallest `step` across the tiered `price_ranges` array (the finest precision the market accepts anywhere on its price curve — orders in coarser tiers must still round to that tier's step).",
    )
    ticker: str = Field(
        ..., description="Native exchange ticker. Kalshi: `ticker`. Polymarket: `slug`."
    )
    title: str = Field(..., description="Market title")
    volume: float = Field(..., description="Total volume (USD)")
    volume_24h: float | None = Field(None, description="24-hour trading volume (USD)")


class Order(BaseModel):
    created_at: AwareDatetime
    fee: float | None = Field(
        None,
        description="Volume-weighted per-contract fee paid for fills resulting from this order, in quote-currency dollars. Kalshi reports it on `create_order` when fills occur immediately; Polymarket charges fees at trade settlement, so this stays `None` on initial create response.",
    )
    filled: float
    id: str
    market_ticker: str
    outcome: str
    price: float
    side: OrderSide
    size: float
    status: OrderStatus
    updated_at: AwareDatetime | None = None


class PriceLevel(BaseModel):
    price: Number
    size: float


class PriceLevelChange(BaseModel):
    price: Number
    side: PriceLevelSide
    size: float


class Series(BaseModel):
    category: str | None = None
    fee_type: str | None = None
    frequency: str | None = None
    last_updated_ts: AwareDatetime | None = None
    numeric_id: str | None = Field(
        None,
        description='Polymarket\'s numeric REST id for the series (e.g. `"10345"`). None on Kalshi (no separate numeric series surface).',
    )
    settlement_sources: list[SettlementSource] | None = Field([], validate_default=True)
    tags: list[str] | None = []
    ticker: str = Field(
        ...,
        description='Native series identifier. Kalshi: `ticker` (e.g. `"KXPRES"`). Polymarket: the series\'s `ticker` field, falling back to `slug` when `ticker` is null upstream.',
    )
    title: str
    volume: float | None = None


class WsUpdate2(BaseModel):
    asset_id: str
    changes: list[PriceLevelChange]
    exchange_ts: conint(ge=0) | None = None
    kind: Kind6
    local_ts_ms: conint(ge=0)
    market_id: str
    seq: conint(ge=0)


class WsUpdate5(BaseModel):
    fill: ActivityFill
    kind: Kind9
    local_ts_ms: conint(ge=0)


class MarketLineage(BaseModel):
    event: Event | None = None
    market: Market
    series: Series | None = None


class Orderbook(BaseModel):
    asks: list[PriceLevel]
    asset_id: str
    bids: list[PriceLevel]
    hash: str | None = Field(
        None,
        description="Exchange-provided hash for verifying book state integrity during replay. Polymarket: present on `book` snapshot events.",
    )
    last_update_id: conint(ge=0) | None = None
    timestamp: AwareDatetime | None = None


class WsUpdate1(BaseModel):
    asset_id: str
    book: Orderbook
    exchange_ts: conint(ge=0) | None = None
    kind: Kind5
    local_ts_ms: conint(ge=0)
    market_id: str
    seq: conint(ge=0)


class WsUpdate(RootModel[WsUpdate1 | WsUpdate2 | WsUpdate3 | WsUpdate4 | WsUpdate5]):
    root: WsUpdate1 | WsUpdate2 | WsUpdate3 | WsUpdate4 | WsUpdate5 = Field(
        ...,
        description="Every per-market event the WebSocket surface emits. Closed tagged union; no untyped escape hatch in the stable enum. If an exchange grows a payload we want to surface in raw form, add a separate `raw_events()` stream rather than another `WsUpdate` variant — keeps consumer `match` exhaustiveness honest.",
        title="WsUpdate",
    )
