# generated by datamodel-codegen:
#   filename:  openpx.schema.json
#   timestamp: 2026-04-18T00:36:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, conint


class OpenPX(RootModel[Any]):
    root: Any = Field(
        ...,
        description="Auto-generated JSON Schema for OpenPX core types",
        title="OpenPX",
    )


class ActivityTrade(BaseModel):
    aggressor_side: str | None = None
    asset_id: str
    fee_rate_bps: conint(ge=0) | None = Field(
        None,
        description="Fee rate in basis points (e.g. 0 = no fee, 200 = 2%). Polymarket: present on `last_trade_price` events.",
    )
    market_id: str
    outcome: str | None = None
    price: float
    side: str | None = None
    size: float
    source_channel: str
    timestamp: AwareDatetime | None = None
    trade_id: str | None = None


class Candlestick(BaseModel):
    close: float
    high: float
    low: float
    open: float
    open_interest: float | None = Field(
        None,
        description="Open interest at this candle's close. Only available from exchanges that report it (e.g., Kalshi).",
    )
    timestamp: AwareDatetime = Field(
        ...,
        description="Period start timestamp (UTC). lightweight-charts expects start-of-period.",
    )
    volume: float = Field(
        ...,
        description="Trade volume in contracts. 0.0 if exchange doesn't provide volume.",
    )


class ExchangeInfo(BaseModel):
    has_approvals: bool
    has_cancel_order: bool
    has_create_order: bool
    has_fetch_balance: bool
    has_fetch_fills: bool
    has_fetch_markets: bool
    has_fetch_orderbook: bool
    has_fetch_orderbook_history: bool
    has_fetch_positions: bool
    has_fetch_price_history: bool
    has_fetch_trades: bool
    has_fetch_user_activity: bool
    has_refresh_balance: bool
    has_websocket: bool
    id: str
    name: str


class FetchOrdersParams(BaseModel):
    market_id: str | None = None


class FetchUserActivityParams(BaseModel):
    address: str
    limit: conint(ge=0) | None = None


class LiquidityRole(Enum):
    maker = "maker"
    taker = "taker"


class MarketStatus(Enum):
    active = "active"
    closed = "closed"
    resolved = "resolved"


class MarketStatusFilter(Enum):
    active = "active"
    closed = "closed"
    resolved = "resolved"
    all = "all"


class MarketTrade(BaseModel):
    aggressor_side: str | None = None
    id: str | None = None
    no_price: float | None = None
    outcome: str | None = None
    price: float
    side: str | None = None
    size: float
    source_channel: str
    taker_address: str | None = None
    timestamp: AwareDatetime
    tx_hash: str | None = None
    yes_price: float | None = None


class MarketType(Enum):
    binary = "binary"
    categorical = "categorical"
    scalar = "scalar"


class OrderSide(Enum):
    buy = "buy"
    sell = "sell"


class OrderStatus(Enum):
    pending = "pending"
    open = "open"
    filled = "filled"
    partially_filled = "partially_filled"
    cancelled = "cancelled"
    rejected = "rejected"


class OrderType(Enum):
    gtc = "gtc"
    ioc = "ioc"
    fok = "fok"


class OrderbookHistoryRequest(BaseModel):
    cursor: str | None = None
    end_ts: int | None = None
    limit: conint(ge=0) | None = None
    market_id: str
    start_ts: int | None = None
    token_id: str | None = None


class OrderbookRequest(BaseModel):
    market_id: str
    outcome: str | None = None
    token_id: str | None = None


class OutcomeToken(BaseModel):
    outcome: str
    token_id: str


class Position(BaseModel):
    average_price: float
    current_price: float
    market_id: str
    outcome: str
    size: float


class PriceHistoryInterval(Enum):
    field_1m = "1m"
    field_1h = "1h"
    field_6h = "6h"
    field_1d = "1d"
    field_1w = "1w"
    max = "max"


class PriceHistoryRequest(BaseModel):
    condition_id: str | None = Field(
        None, description="Condition ID for OI enrichment (Polymarket)."
    )
    end_ts: int | None = Field(None, description="Unix seconds")
    interval: PriceHistoryInterval
    market_id: str
    outcome: str | None = None
    start_ts: int | None = Field(None, description="Unix seconds")
    token_id: str | None = None


class PriceLevelSide(Enum):
    bid = "bid"
    ask = "ask"


class TradesRequest(BaseModel):
    cursor: str | None = Field(
        None, description="Opaque pagination cursor from a previous response."
    )
    end_ts: int | None = Field(None, description="Unix seconds (inclusive)")
    limit: conint(ge=0) | None = Field(
        None,
        description="Max number of trades to return (exchange-specific caps may apply).",
    )
    market_id: str = Field(..., description="Exchange-native market identifier.")
    market_ref: str | None = Field(
        None,
        description="Optional alternate market identifier for trade endpoints (e.g., Polymarket conditionId). When provided, exchanges should prefer this over `market_id`.",
    )
    outcome: str | None = None
    start_ts: int | None = Field(None, description="Unix seconds (inclusive)")
    token_id: str | None = None


class Number(RootModel[float]):
    root: float


class ActivityEvent1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Trade: ActivityTrade


class ActivityFill(BaseModel):
    asset_id: str
    fee: float | None = Field(
        None,
        description="Fee charged for this fill. Opinion: `fee` from `trade.record.new`.",
    )
    fill_id: str | None = None
    liquidity_role: LiquidityRole | None = None
    market_id: str
    order_id: str | None = None
    outcome: str | None = None
    price: float
    side: str | None = None
    size: float
    source_channel: str
    timestamp: AwareDatetime | None = None
    tx_hash: str | None = Field(
        None,
        description="On-chain transaction hash. Opinion: `txHash` from `trade.record.new`.",
    )


class FetchMarketsParams(BaseModel):
    cursor: str | None = Field(
        None,
        description="Exchange-specific cursor (offset, page number, or cursor string)",
    )
    event_id: str | None = Field(
        None,
        description='Fetch all markets within a specific event. Pass a Kalshi event ticker (e.g., `"KXBTC-25MAR14"`), a Polymarket event ID or slug (e.g., `"903"` or `"will-trump-win-2024"`), or an Opinion market slug (e.g., `"btc-price-daily"`) to get its child markets. When set, `series_id`, `cursor`, and `limit` are ignored (not paginated). `status` filtering is still applied client-side.',
    )
    limit: conint(ge=0) | None = None
    series_id: str | None = Field(
        None,
        description='Filter by series (Kalshi and Polymarket). Both exchanges organize markets as Series → Events → Markets. Pass a Kalshi series ticker (e.g., `"KXBTC"`) or a Polymarket series ID (e.g., `"10345"`) to fetch only markets in that series.',
    )
    status: MarketStatusFilter | None = Field(
        None,
        description="Filter by market status. Defaults to Active at the exchange level when None. Use `MarketStatusFilter::All` to fetch markets of any status.",
    )


class Fill(BaseModel):
    created_at: AwareDatetime
    fee: float
    fill_id: str
    is_taker: bool
    market_id: str
    order_id: str
    outcome: str
    price: float
    side: OrderSide
    size: float


class Market(BaseModel):
    accepting_orders: bool | None = Field(
        False, description="Whether the market is currently accepting orders"
    )
    best_ask: float | None = Field(None, description="Best ask price (normalized 0-1)")
    best_bid: float | None = Field(None, description="Best bid price (normalized 0-1)")
    can_close_early: bool | None = Field(None, description="Kalshi: can close early")
    chain_id: str | None = Field(None, description="Chain ID for on-chain markets")
    close_time: AwareDatetime | None = Field(None, description="Market close time")
    condition_id: str | None = Field(None, description="Condition ID for CTF")
    created_at: AwareDatetime | None = Field(None, description="Market creation time")
    denomination_token: str | None = Field(
        None, description="Denomination token (e.g. USDC address)"
    )
    description: str = Field(..., description="Full description")
    event_id: str | None = Field(
        None, description="Canonical OpenPX event ID for cross-exchange event grouping."
    )
    exchange: str = Field(
        ..., description="Exchange identifier (kalshi, polymarket, opinion)"
    )
    group_id: str | None = Field(
        None, description="Source-native event/group ID from the exchange."
    )
    icon_url: str | None = Field(None, description="Market icon URL")
    id: str = Field(..., description="Native exchange market ID")
    image_url: str | None = Field(None, description="Market image URL")
    last_trade_price: float | None = Field(
        None, description="Last trade price (normalized 0-1)"
    )
    liquidity: float | None = Field(None, description="Current liquidity")
    maker_fee_bps: float | None = Field(
        None, description="Maker fee rate (basis points)"
    )
    market_type: MarketType = Field(..., description="Market type classification")
    min_order_size: float | None = Field(
        None, description="Minimum order size (contracts)"
    )
    neg_risk: bool | None = Field(None, description="Polymarket: neg-risk flag")
    neg_risk_market_id: str | None = Field(
        None, description="Polymarket: neg-risk market ID"
    )
    notional_value: float | None = Field(
        None, description="Notional value per contract (Kalshi)"
    )
    open_interest: float | None = Field(None, description="Current open interest")
    open_time: AwareDatetime | None = Field(None, description="Market open time")
    openpx_id: str = Field(..., description="Primary key: {exchange}:{native_id}")
    outcome_prices: dict[str, float] | None = Field(
        None,
        description='Outcome prices from the REST API (e.g., {"Yes": 0.65, "No": 0.35})',
    )
    outcome_tokens: list[OutcomeToken] | None = Field(
        [],
        description="Outcome-to-token mapping for orderbook subscriptions",
        validate_default=True,
    )
    outcomes: list[str] | None = Field(
        [], description='Outcome labels (e.g., ["Yes", "No"] for binary markets)'
    )
    previous_price: float | None = Field(None, description="Kalshi: previous price")
    price_change_1d: float | None = Field(
        None, description="24-hour YES price change (decimal, e.g. 0.05 = +5%)"
    )
    price_change_1h: float | None = Field(None, description="1-hour YES price change")
    price_change_1mo: float | None = Field(None, description="30-day YES price change")
    price_change_1wk: float | None = Field(None, description="7-day YES price change")
    price_level_structure: str | None = Field(
        None, description="Kalshi sub-penny pricing structure"
    )
    question: str | None = Field(
        None, description="Market question (may differ from title)"
    )
    question_id: str | None = Field(
        None, description="Question ID (Opinion, Polymarket)"
    )
    result: str | None = Field(None, description="Resolution result")
    rules: str | None = Field(None, description="Resolution rules")
    settlement_time: AwareDatetime | None = Field(
        None, description="Settlement / resolution time"
    )
    settlement_value: float | None = Field(None, description="Kalshi: settlement value")
    slug: str | None = Field(None, description="URL-friendly identifier")
    spread: float | None = Field(None, description="Bid-ask spread (decimal)")
    status: MarketStatus = Field(
        ..., description="Normalized status: Active, Closed, Resolved"
    )
    taker_fee_bps: float | None = Field(
        None, description="Taker fee rate (basis points)"
    )
    tick_size: float | None = Field(
        None,
        description="Tick size (minimum price increment, normalized decimal e.g. 0.01)",
    )
    title: str = Field(..., description="Market title")
    token_id_no: str | None = Field(None, description="No outcome token ID")
    token_id_yes: str | None = Field(None, description="Yes outcome token ID")
    volume: float = Field(..., description="Total volume (USD)")
    volume_1mo: float | None = Field(
        None, description="30-day rolling trading volume (USD)"
    )
    volume_1wk: float | None = Field(
        None, description="7-day rolling trading volume (USD)"
    )
    volume_24h: float | None = Field(None, description="24-hour trading volume (USD)")


class Order(BaseModel):
    created_at: AwareDatetime
    filled: float
    id: str
    market_id: str
    outcome: str
    price: float
    side: OrderSide
    size: float
    status: OrderStatus
    updated_at: AwareDatetime | None = None


class PriceLevel(BaseModel):
    price: Number
    size: float


class PriceLevelChange(BaseModel):
    price: Number
    side: PriceLevelSide
    size: float


class ActivityEvent2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Fill: ActivityFill


class ActivityEvent(RootModel[ActivityEvent1 | ActivityEvent2]):
    root: ActivityEvent1 | ActivityEvent2 = Field(..., title="ActivityEvent")


class Orderbook(BaseModel):
    asks: list[PriceLevel]
    asset_id: str
    bids: list[PriceLevel]
    hash: str | None = Field(
        None,
        description="Exchange-provided hash for verifying book state integrity during replay. Polymarket: present on `book` snapshot events.",
    )
    last_update_id: conint(ge=0) | None = None
    market_id: str
    timestamp: AwareDatetime | None = None


class OrderbookSnapshot(BaseModel):
    asks: list[PriceLevel]
    bids: list[PriceLevel]
    hash: str | None = None
    recorded_at: AwareDatetime | None = None
    timestamp: AwareDatetime
